// Code generated by ent, DO NOT EDIT.

package userdevice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userdevice type in the database.
	Label = "user_device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDeviceHash holds the string denoting the device_hash field in the database.
	FieldDeviceHash = "device_hash"
	// FieldFingerprintVersion holds the string denoting the fingerprint_version field in the database.
	FieldFingerprintVersion = "fingerprint_version"
	// FieldInstallID holds the string denoting the install_id field in the database.
	FieldInstallID = "install_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldArch holds the string denoting the arch field in the database.
	FieldArch = "arch"
	// FieldAppVersion holds the string denoting the app_version field in the database.
	FieldAppVersion = "app_version"
	// FieldClaimRedeemCodeID holds the string denoting the claim_redeem_code_id field in the database.
	FieldClaimRedeemCodeID = "claim_redeem_code_id"
	// FieldLoginRedeemCodeID holds the string denoting the login_redeem_code_id field in the database.
	FieldLoginRedeemCodeID = "login_redeem_code_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFirstClaimedAt holds the string denoting the first_claimed_at field in the database.
	FieldFirstClaimedAt = "first_claimed_at"
	// FieldLastClaimedAt holds the string denoting the last_claimed_at field in the database.
	FieldLastClaimedAt = "last_claimed_at"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeClaimRedeemCode holds the string denoting the claim_redeem_code edge name in mutations.
	EdgeClaimRedeemCode = "claim_redeem_code"
	// EdgeLoginRedeemCode holds the string denoting the login_redeem_code edge name in mutations.
	EdgeLoginRedeemCode = "login_redeem_code"
	// Table holds the table name of the userdevice in the database.
	Table = "user_devices"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_devices"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ClaimRedeemCodeTable is the table that holds the claim_redeem_code relation/edge.
	ClaimRedeemCodeTable = "user_devices"
	// ClaimRedeemCodeInverseTable is the table name for the RedeemCode entity.
	// It exists in this package in order to avoid circular dependency with the "redeemcode" package.
	ClaimRedeemCodeInverseTable = "redeem_codes"
	// ClaimRedeemCodeColumn is the table column denoting the claim_redeem_code relation/edge.
	ClaimRedeemCodeColumn = "claim_redeem_code_id"
	// LoginRedeemCodeTable is the table that holds the login_redeem_code relation/edge.
	LoginRedeemCodeTable = "user_devices"
	// LoginRedeemCodeInverseTable is the table name for the RedeemCode entity.
	// It exists in this package in order to avoid circular dependency with the "redeemcode" package.
	LoginRedeemCodeInverseTable = "redeem_codes"
	// LoginRedeemCodeColumn is the table column denoting the login_redeem_code relation/edge.
	LoginRedeemCodeColumn = "login_redeem_code_id"
)

// Columns holds all SQL columns for userdevice fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDeviceHash,
	FieldFingerprintVersion,
	FieldInstallID,
	FieldPlatform,
	FieldArch,
	FieldAppVersion,
	FieldClaimRedeemCodeID,
	FieldLoginRedeemCodeID,
	FieldStatus,
	FieldFirstClaimedAt,
	FieldLastClaimedAt,
	FieldLastLoginAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DeviceHashValidator is a validator for the "device_hash" field. It is called by the builders before save.
	DeviceHashValidator func(string) error
	// DefaultFingerprintVersion holds the default value on creation for the "fingerprint_version" field.
	DefaultFingerprintVersion int
	// InstallIDValidator is a validator for the "install_id" field. It is called by the builders before save.
	InstallIDValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// ArchValidator is a validator for the "arch" field. It is called by the builders before save.
	ArchValidator func(string) error
	// AppVersionValidator is a validator for the "app_version" field. It is called by the builders before save.
	AppVersionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFirstClaimedAt holds the default value on creation for the "first_claimed_at" field.
	DefaultFirstClaimedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserDevice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDeviceHash orders the results by the device_hash field.
func ByDeviceHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceHash, opts...).ToFunc()
}

// ByFingerprintVersion orders the results by the fingerprint_version field.
func ByFingerprintVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprintVersion, opts...).ToFunc()
}

// ByInstallID orders the results by the install_id field.
func ByInstallID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByArch orders the results by the arch field.
func ByArch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArch, opts...).ToFunc()
}

// ByAppVersion orders the results by the app_version field.
func ByAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersion, opts...).ToFunc()
}

// ByClaimRedeemCodeID orders the results by the claim_redeem_code_id field.
func ByClaimRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimRedeemCodeID, opts...).ToFunc()
}

// ByLoginRedeemCodeID orders the results by the login_redeem_code_id field.
func ByLoginRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginRedeemCodeID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFirstClaimedAt orders the results by the first_claimed_at field.
func ByFirstClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstClaimedAt, opts...).ToFunc()
}

// ByLastClaimedAt orders the results by the last_claimed_at field.
func ByLastClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastClaimedAt, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByClaimRedeemCodeField orders the results by claim_redeem_code field.
func ByClaimRedeemCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClaimRedeemCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByLoginRedeemCodeField orders the results by login_redeem_code field.
func ByLoginRedeemCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLoginRedeemCodeStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newClaimRedeemCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClaimRedeemCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClaimRedeemCodeTable, ClaimRedeemCodeColumn),
	)
}
func newLoginRedeemCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LoginRedeemCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LoginRedeemCodeTable, LoginRedeemCodeColumn),
	)
}
