ALTER TABLE payment_orders
    ADD COLUMN IF NOT EXISTS payment_currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    ADD COLUMN IF NOT EXISTS payment_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ledger_currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    ADD COLUMN IF NOT EXISTS ledger_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fx_rate_payment_to_ledger DECIMAL(20,8) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS fx_source VARCHAR(32),
    ADD COLUMN IF NOT EXISTS fx_timestamp TIMESTAMPTZ;
