// Code generated by ent, DO NOT EDIT.

package catalogoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the catalogoutbox type in the database.
	Label = "catalog_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldPublicationEpoch holds the string denoting the publication_epoch field in the database.
	FieldPublicationEpoch = "publication_epoch"
	// FieldCatalogRevisionID holds the string denoting the catalog_revision_id field in the database.
	FieldCatalogRevisionID = "catalog_revision_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldDedupKey holds the string denoting the dedup_key field in the database.
	FieldDedupKey = "dedup_key"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the catalogoutbox in the database.
	Table = "catalog_outbox"
)

// Columns holds all SQL columns for catalogoutbox fields.
var Columns = []string{
	FieldID,
	FieldEventType,
	FieldScope,
	FieldPublicationEpoch,
	FieldCatalogRevisionID,
	FieldModelID,
	FieldPayload,
	FieldDedupKey,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CatalogOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByPublicationEpoch orders the results by the publication_epoch field.
func ByPublicationEpoch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicationEpoch, opts...).ToFunc()
}

// ByCatalogRevisionID orders the results by the catalog_revision_id field.
func ByCatalogRevisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCatalogRevisionID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByDedupKey orders the results by the dedup_key field.
func ByDedupKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDedupKey, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
