// Code generated by ent, DO NOT EDIT.

package cataloglifecycleaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cataloglifecycleaudit type in the database.
	Label = "catalog_lifecycle_audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldCatalogRevisionID holds the string denoting the catalog_revision_id field in the database.
	FieldCatalogRevisionID = "catalog_revision_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldActorType holds the string denoting the actor_type field in the database.
	FieldActorType = "actor_type"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldBeforeState holds the string denoting the before_state field in the database.
	FieldBeforeState = "before_state"
	// FieldAfterState holds the string denoting the after_state field in the database.
	FieldAfterState = "after_state"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldCorrelationID holds the string denoting the correlation_id field in the database.
	FieldCorrelationID = "correlation_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the cataloglifecycleaudit in the database.
	Table = "catalog_lifecycle_audits"
)

// Columns holds all SQL columns for cataloglifecycleaudit fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldCatalogRevisionID,
	FieldAction,
	FieldActorType,
	FieldActorUserID,
	FieldReason,
	FieldBeforeState,
	FieldAfterState,
	FieldRequestID,
	FieldCorrelationID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CatalogLifecycleAudit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByCatalogRevisionID orders the results by the catalog_revision_id field.
func ByCatalogRevisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCatalogRevisionID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByActorType orders the results by the actor_type field.
func ByActorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorType, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByCorrelationID orders the results by the correlation_id field.
func ByCorrelationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrelationID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
