// Code generated by ent, DO NOT EDIT.

package cataloglifecycleaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldID, id))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldModelID, v))
}

// CatalogRevisionID applies equality check predicate on the "catalog_revision_id" field. It's identical to CatalogRevisionIDEQ.
func CatalogRevisionID(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldCatalogRevisionID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldAction, v))
}

// ActorType applies equality check predicate on the "actor_type" field. It's identical to ActorTypeEQ.
func ActorType(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldActorType, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldActorUserID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldReason, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldRequestID, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldCorrelationID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldModelID, v))
}

// ModelIDIsNil applies the IsNil predicate on the "model_id" field.
func ModelIDIsNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIsNull(FieldModelID))
}

// ModelIDNotNil applies the NotNil predicate on the "model_id" field.
func ModelIDNotNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotNull(FieldModelID))
}

// CatalogRevisionIDEQ applies the EQ predicate on the "catalog_revision_id" field.
func CatalogRevisionIDEQ(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldCatalogRevisionID, v))
}

// CatalogRevisionIDNEQ applies the NEQ predicate on the "catalog_revision_id" field.
func CatalogRevisionIDNEQ(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldCatalogRevisionID, v))
}

// CatalogRevisionIDIn applies the In predicate on the "catalog_revision_id" field.
func CatalogRevisionIDIn(vs ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldCatalogRevisionID, vs...))
}

// CatalogRevisionIDNotIn applies the NotIn predicate on the "catalog_revision_id" field.
func CatalogRevisionIDNotIn(vs ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldCatalogRevisionID, vs...))
}

// CatalogRevisionIDGT applies the GT predicate on the "catalog_revision_id" field.
func CatalogRevisionIDGT(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldCatalogRevisionID, v))
}

// CatalogRevisionIDGTE applies the GTE predicate on the "catalog_revision_id" field.
func CatalogRevisionIDGTE(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldCatalogRevisionID, v))
}

// CatalogRevisionIDLT applies the LT predicate on the "catalog_revision_id" field.
func CatalogRevisionIDLT(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldCatalogRevisionID, v))
}

// CatalogRevisionIDLTE applies the LTE predicate on the "catalog_revision_id" field.
func CatalogRevisionIDLTE(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldCatalogRevisionID, v))
}

// CatalogRevisionIDIsNil applies the IsNil predicate on the "catalog_revision_id" field.
func CatalogRevisionIDIsNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIsNull(FieldCatalogRevisionID))
}

// CatalogRevisionIDNotNil applies the NotNil predicate on the "catalog_revision_id" field.
func CatalogRevisionIDNotNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotNull(FieldCatalogRevisionID))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContainsFold(FieldAction, v))
}

// ActorTypeEQ applies the EQ predicate on the "actor_type" field.
func ActorTypeEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldActorType, v))
}

// ActorTypeNEQ applies the NEQ predicate on the "actor_type" field.
func ActorTypeNEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldActorType, v))
}

// ActorTypeIn applies the In predicate on the "actor_type" field.
func ActorTypeIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldActorType, vs...))
}

// ActorTypeNotIn applies the NotIn predicate on the "actor_type" field.
func ActorTypeNotIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldActorType, vs...))
}

// ActorTypeGT applies the GT predicate on the "actor_type" field.
func ActorTypeGT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldActorType, v))
}

// ActorTypeGTE applies the GTE predicate on the "actor_type" field.
func ActorTypeGTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldActorType, v))
}

// ActorTypeLT applies the LT predicate on the "actor_type" field.
func ActorTypeLT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldActorType, v))
}

// ActorTypeLTE applies the LTE predicate on the "actor_type" field.
func ActorTypeLTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldActorType, v))
}

// ActorTypeContains applies the Contains predicate on the "actor_type" field.
func ActorTypeContains(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContains(FieldActorType, v))
}

// ActorTypeHasPrefix applies the HasPrefix predicate on the "actor_type" field.
func ActorTypeHasPrefix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasPrefix(FieldActorType, v))
}

// ActorTypeHasSuffix applies the HasSuffix predicate on the "actor_type" field.
func ActorTypeHasSuffix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasSuffix(FieldActorType, v))
}

// ActorTypeEqualFold applies the EqualFold predicate on the "actor_type" field.
func ActorTypeEqualFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEqualFold(FieldActorType, v))
}

// ActorTypeContainsFold applies the ContainsFold predicate on the "actor_type" field.
func ActorTypeContainsFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContainsFold(FieldActorType, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int64) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldActorUserID, v))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotNull(FieldActorUserID))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContainsFold(FieldReason, v))
}

// BeforeStateIsNil applies the IsNil predicate on the "before_state" field.
func BeforeStateIsNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIsNull(FieldBeforeState))
}

// BeforeStateNotNil applies the NotNil predicate on the "before_state" field.
func BeforeStateNotNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotNull(FieldBeforeState))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContainsFold(FieldRequestID, v))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldContainsFold(FieldCorrelationID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CatalogLifecycleAudit) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CatalogLifecycleAudit) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CatalogLifecycleAudit) predicate.CatalogLifecycleAudit {
	return predicate.CatalogLifecycleAudit(sql.NotPredicates(p))
}
