// Code generated by ent, DO NOT EDIT.

package catalogmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldID, id))
}

// CanonicalKey applies equality check predicate on the "canonical_key" field. It's identical to CanonicalKeyEQ.
func CanonicalKey(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldCanonicalKey, v))
}

// CanonicalKeyNormalized applies equality check predicate on the "canonical_key_normalized" field. It's identical to CanonicalKeyNormalizedEQ.
func CanonicalKeyNormalized(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldCanonicalKeyNormalized, v))
}

// OperatorState applies equality check predicate on the "operator_state" field. It's identical to OperatorStateEQ.
func OperatorState(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldOperatorState, v))
}

// OperatorReason applies equality check predicate on the "operator_reason" field. It's identical to OperatorReasonEQ.
func OperatorReason(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldOperatorReason, v))
}

// ReplacementModelID applies equality check predicate on the "replacement_model_id" field. It's identical to ReplacementModelIDEQ.
func ReplacementModelID(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldReplacementModelID, v))
}

// OperatorVersion applies equality check predicate on the "operator_version" field. It's identical to OperatorVersionEQ.
func OperatorVersion(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldOperatorVersion, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastOperatorChangeAt applies equality check predicate on the "last_operator_change_at" field. It's identical to LastOperatorChangeAtEQ.
func LastOperatorChangeAt(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldLastOperatorChangeAt, v))
}

// RetiredAt applies equality check predicate on the "retired_at" field. It's identical to RetiredAtEQ.
func RetiredAt(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldRetiredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// CanonicalKeyEQ applies the EQ predicate on the "canonical_key" field.
func CanonicalKeyEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldCanonicalKey, v))
}

// CanonicalKeyNEQ applies the NEQ predicate on the "canonical_key" field.
func CanonicalKeyNEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldCanonicalKey, v))
}

// CanonicalKeyIn applies the In predicate on the "canonical_key" field.
func CanonicalKeyIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldCanonicalKey, vs...))
}

// CanonicalKeyNotIn applies the NotIn predicate on the "canonical_key" field.
func CanonicalKeyNotIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldCanonicalKey, vs...))
}

// CanonicalKeyGT applies the GT predicate on the "canonical_key" field.
func CanonicalKeyGT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldCanonicalKey, v))
}

// CanonicalKeyGTE applies the GTE predicate on the "canonical_key" field.
func CanonicalKeyGTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldCanonicalKey, v))
}

// CanonicalKeyLT applies the LT predicate on the "canonical_key" field.
func CanonicalKeyLT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldCanonicalKey, v))
}

// CanonicalKeyLTE applies the LTE predicate on the "canonical_key" field.
func CanonicalKeyLTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldCanonicalKey, v))
}

// CanonicalKeyContains applies the Contains predicate on the "canonical_key" field.
func CanonicalKeyContains(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContains(FieldCanonicalKey, v))
}

// CanonicalKeyHasPrefix applies the HasPrefix predicate on the "canonical_key" field.
func CanonicalKeyHasPrefix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasPrefix(FieldCanonicalKey, v))
}

// CanonicalKeyHasSuffix applies the HasSuffix predicate on the "canonical_key" field.
func CanonicalKeyHasSuffix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasSuffix(FieldCanonicalKey, v))
}

// CanonicalKeyEqualFold applies the EqualFold predicate on the "canonical_key" field.
func CanonicalKeyEqualFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEqualFold(FieldCanonicalKey, v))
}

// CanonicalKeyContainsFold applies the ContainsFold predicate on the "canonical_key" field.
func CanonicalKeyContainsFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContainsFold(FieldCanonicalKey, v))
}

// CanonicalKeyNormalizedEQ applies the EQ predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedNEQ applies the NEQ predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedNEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedIn applies the In predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldCanonicalKeyNormalized, vs...))
}

// CanonicalKeyNormalizedNotIn applies the NotIn predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedNotIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldCanonicalKeyNormalized, vs...))
}

// CanonicalKeyNormalizedGT applies the GT predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedGT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedGTE applies the GTE predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedGTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedLT applies the LT predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedLT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedLTE applies the LTE predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedLTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedContains applies the Contains predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedContains(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContains(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedHasPrefix applies the HasPrefix predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedHasPrefix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasPrefix(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedHasSuffix applies the HasSuffix predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedHasSuffix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasSuffix(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedEqualFold applies the EqualFold predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedEqualFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEqualFold(FieldCanonicalKeyNormalized, v))
}

// CanonicalKeyNormalizedContainsFold applies the ContainsFold predicate on the "canonical_key_normalized" field.
func CanonicalKeyNormalizedContainsFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContainsFold(FieldCanonicalKeyNormalized, v))
}

// OperatorStateEQ applies the EQ predicate on the "operator_state" field.
func OperatorStateEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldOperatorState, v))
}

// OperatorStateNEQ applies the NEQ predicate on the "operator_state" field.
func OperatorStateNEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldOperatorState, v))
}

// OperatorStateIn applies the In predicate on the "operator_state" field.
func OperatorStateIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldOperatorState, vs...))
}

// OperatorStateNotIn applies the NotIn predicate on the "operator_state" field.
func OperatorStateNotIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldOperatorState, vs...))
}

// OperatorStateGT applies the GT predicate on the "operator_state" field.
func OperatorStateGT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldOperatorState, v))
}

// OperatorStateGTE applies the GTE predicate on the "operator_state" field.
func OperatorStateGTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldOperatorState, v))
}

// OperatorStateLT applies the LT predicate on the "operator_state" field.
func OperatorStateLT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldOperatorState, v))
}

// OperatorStateLTE applies the LTE predicate on the "operator_state" field.
func OperatorStateLTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldOperatorState, v))
}

// OperatorStateContains applies the Contains predicate on the "operator_state" field.
func OperatorStateContains(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContains(FieldOperatorState, v))
}

// OperatorStateHasPrefix applies the HasPrefix predicate on the "operator_state" field.
func OperatorStateHasPrefix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasPrefix(FieldOperatorState, v))
}

// OperatorStateHasSuffix applies the HasSuffix predicate on the "operator_state" field.
func OperatorStateHasSuffix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasSuffix(FieldOperatorState, v))
}

// OperatorStateEqualFold applies the EqualFold predicate on the "operator_state" field.
func OperatorStateEqualFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEqualFold(FieldOperatorState, v))
}

// OperatorStateContainsFold applies the ContainsFold predicate on the "operator_state" field.
func OperatorStateContainsFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContainsFold(FieldOperatorState, v))
}

// OperatorReasonEQ applies the EQ predicate on the "operator_reason" field.
func OperatorReasonEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldOperatorReason, v))
}

// OperatorReasonNEQ applies the NEQ predicate on the "operator_reason" field.
func OperatorReasonNEQ(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldOperatorReason, v))
}

// OperatorReasonIn applies the In predicate on the "operator_reason" field.
func OperatorReasonIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldOperatorReason, vs...))
}

// OperatorReasonNotIn applies the NotIn predicate on the "operator_reason" field.
func OperatorReasonNotIn(vs ...string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldOperatorReason, vs...))
}

// OperatorReasonGT applies the GT predicate on the "operator_reason" field.
func OperatorReasonGT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldOperatorReason, v))
}

// OperatorReasonGTE applies the GTE predicate on the "operator_reason" field.
func OperatorReasonGTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldOperatorReason, v))
}

// OperatorReasonLT applies the LT predicate on the "operator_reason" field.
func OperatorReasonLT(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldOperatorReason, v))
}

// OperatorReasonLTE applies the LTE predicate on the "operator_reason" field.
func OperatorReasonLTE(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldOperatorReason, v))
}

// OperatorReasonContains applies the Contains predicate on the "operator_reason" field.
func OperatorReasonContains(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContains(FieldOperatorReason, v))
}

// OperatorReasonHasPrefix applies the HasPrefix predicate on the "operator_reason" field.
func OperatorReasonHasPrefix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasPrefix(FieldOperatorReason, v))
}

// OperatorReasonHasSuffix applies the HasSuffix predicate on the "operator_reason" field.
func OperatorReasonHasSuffix(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldHasSuffix(FieldOperatorReason, v))
}

// OperatorReasonIsNil applies the IsNil predicate on the "operator_reason" field.
func OperatorReasonIsNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIsNull(FieldOperatorReason))
}

// OperatorReasonNotNil applies the NotNil predicate on the "operator_reason" field.
func OperatorReasonNotNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotNull(FieldOperatorReason))
}

// OperatorReasonEqualFold applies the EqualFold predicate on the "operator_reason" field.
func OperatorReasonEqualFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEqualFold(FieldOperatorReason, v))
}

// OperatorReasonContainsFold applies the ContainsFold predicate on the "operator_reason" field.
func OperatorReasonContainsFold(v string) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldContainsFold(FieldOperatorReason, v))
}

// ReplacementModelIDEQ applies the EQ predicate on the "replacement_model_id" field.
func ReplacementModelIDEQ(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldReplacementModelID, v))
}

// ReplacementModelIDNEQ applies the NEQ predicate on the "replacement_model_id" field.
func ReplacementModelIDNEQ(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldReplacementModelID, v))
}

// ReplacementModelIDIn applies the In predicate on the "replacement_model_id" field.
func ReplacementModelIDIn(vs ...int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldReplacementModelID, vs...))
}

// ReplacementModelIDNotIn applies the NotIn predicate on the "replacement_model_id" field.
func ReplacementModelIDNotIn(vs ...int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldReplacementModelID, vs...))
}

// ReplacementModelIDGT applies the GT predicate on the "replacement_model_id" field.
func ReplacementModelIDGT(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldReplacementModelID, v))
}

// ReplacementModelIDGTE applies the GTE predicate on the "replacement_model_id" field.
func ReplacementModelIDGTE(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldReplacementModelID, v))
}

// ReplacementModelIDLT applies the LT predicate on the "replacement_model_id" field.
func ReplacementModelIDLT(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldReplacementModelID, v))
}

// ReplacementModelIDLTE applies the LTE predicate on the "replacement_model_id" field.
func ReplacementModelIDLTE(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldReplacementModelID, v))
}

// ReplacementModelIDIsNil applies the IsNil predicate on the "replacement_model_id" field.
func ReplacementModelIDIsNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIsNull(FieldReplacementModelID))
}

// ReplacementModelIDNotNil applies the NotNil predicate on the "replacement_model_id" field.
func ReplacementModelIDNotNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotNull(FieldReplacementModelID))
}

// OperatorVersionEQ applies the EQ predicate on the "operator_version" field.
func OperatorVersionEQ(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldOperatorVersion, v))
}

// OperatorVersionNEQ applies the NEQ predicate on the "operator_version" field.
func OperatorVersionNEQ(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldOperatorVersion, v))
}

// OperatorVersionIn applies the In predicate on the "operator_version" field.
func OperatorVersionIn(vs ...int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldOperatorVersion, vs...))
}

// OperatorVersionNotIn applies the NotIn predicate on the "operator_version" field.
func OperatorVersionNotIn(vs ...int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldOperatorVersion, vs...))
}

// OperatorVersionGT applies the GT predicate on the "operator_version" field.
func OperatorVersionGT(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldOperatorVersion, v))
}

// OperatorVersionGTE applies the GTE predicate on the "operator_version" field.
func OperatorVersionGTE(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldOperatorVersion, v))
}

// OperatorVersionLT applies the LT predicate on the "operator_version" field.
func OperatorVersionLT(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldOperatorVersion, v))
}

// OperatorVersionLTE applies the LTE predicate on the "operator_version" field.
func OperatorVersionLTE(v int64) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldOperatorVersion, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastOperatorChangeAtEQ applies the EQ predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldLastOperatorChangeAt, v))
}

// LastOperatorChangeAtNEQ applies the NEQ predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtNEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldLastOperatorChangeAt, v))
}

// LastOperatorChangeAtIn applies the In predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldLastOperatorChangeAt, vs...))
}

// LastOperatorChangeAtNotIn applies the NotIn predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtNotIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldLastOperatorChangeAt, vs...))
}

// LastOperatorChangeAtGT applies the GT predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtGT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldLastOperatorChangeAt, v))
}

// LastOperatorChangeAtGTE applies the GTE predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtGTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldLastOperatorChangeAt, v))
}

// LastOperatorChangeAtLT applies the LT predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtLT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldLastOperatorChangeAt, v))
}

// LastOperatorChangeAtLTE applies the LTE predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtLTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldLastOperatorChangeAt, v))
}

// LastOperatorChangeAtIsNil applies the IsNil predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtIsNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIsNull(FieldLastOperatorChangeAt))
}

// LastOperatorChangeAtNotNil applies the NotNil predicate on the "last_operator_change_at" field.
func LastOperatorChangeAtNotNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotNull(FieldLastOperatorChangeAt))
}

// RetiredAtEQ applies the EQ predicate on the "retired_at" field.
func RetiredAtEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldRetiredAt, v))
}

// RetiredAtNEQ applies the NEQ predicate on the "retired_at" field.
func RetiredAtNEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldRetiredAt, v))
}

// RetiredAtIn applies the In predicate on the "retired_at" field.
func RetiredAtIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldRetiredAt, vs...))
}

// RetiredAtNotIn applies the NotIn predicate on the "retired_at" field.
func RetiredAtNotIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldRetiredAt, vs...))
}

// RetiredAtGT applies the GT predicate on the "retired_at" field.
func RetiredAtGT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldRetiredAt, v))
}

// RetiredAtGTE applies the GTE predicate on the "retired_at" field.
func RetiredAtGTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldRetiredAt, v))
}

// RetiredAtLT applies the LT predicate on the "retired_at" field.
func RetiredAtLT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldRetiredAt, v))
}

// RetiredAtLTE applies the LTE predicate on the "retired_at" field.
func RetiredAtLTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldRetiredAt, v))
}

// RetiredAtIsNil applies the IsNil predicate on the "retired_at" field.
func RetiredAtIsNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIsNull(FieldRetiredAt))
}

// RetiredAtNotNil applies the NotNil predicate on the "retired_at" field.
func RetiredAtNotNil() predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotNull(FieldRetiredAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CatalogModel {
	return predicate.CatalogModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CatalogModel) predicate.CatalogModel {
	return predicate.CatalogModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CatalogModel) predicate.CatalogModel {
	return predicate.CatalogModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CatalogModel) predicate.CatalogModel {
	return predicate.CatalogModel(sql.NotPredicates(p))
}
