// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/balancepackage"
)

// BalancePackage is the model entity for the BalancePackage schema.
type BalancePackage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// AmountLedger holds the value of the "amount_ledger" field.
	AmountLedger float64 `json:"amount_ledger,omitempty"`
	// CreditLedger holds the value of the "credit_ledger" field.
	CreditLedger float64 `json:"credit_ledger,omitempty"`
	// BonusLedger holds the value of the "bonus_ledger" field.
	BonusLedger float64 `json:"bonus_ledger,omitempty"`
	// CreditMultiplier holds the value of the "credit_multiplier" field.
	CreditMultiplier float64 `json:"credit_multiplier,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Badge holds the value of the "badge" field.
	Badge string `json:"badge,omitempty"`
	// Popular holds the value of the "popular" field.
	Popular bool `json:"popular,omitempty"`
	// ForSale holds the value of the "for_sale" field.
	ForSale bool `json:"for_sale,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalancePackage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balancepackage.FieldPopular, balancepackage.FieldForSale:
			values[i] = new(sql.NullBool)
		case balancepackage.FieldAmountLedger, balancepackage.FieldCreditLedger, balancepackage.FieldBonusLedger, balancepackage.FieldCreditMultiplier:
			values[i] = new(sql.NullFloat64)
		case balancepackage.FieldID, balancepackage.FieldGroupID, balancepackage.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case balancepackage.FieldCode, balancepackage.FieldLabel, balancepackage.FieldDescription, balancepackage.FieldBadge:
			values[i] = new(sql.NullString)
		case balancepackage.FieldCreatedAt, balancepackage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalancePackage fields.
func (_m *BalancePackage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balancepackage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case balancepackage.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case balancepackage.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case balancepackage.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case balancepackage.FieldAmountLedger:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_ledger", values[i])
			} else if value.Valid {
				_m.AmountLedger = value.Float64
			}
		case balancepackage.FieldCreditLedger:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_ledger", values[i])
			} else if value.Valid {
				_m.CreditLedger = value.Float64
			}
		case balancepackage.FieldBonusLedger:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_ledger", values[i])
			} else if value.Valid {
				_m.BonusLedger = value.Float64
			}
		case balancepackage.FieldCreditMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_multiplier", values[i])
			} else if value.Valid {
				_m.CreditMultiplier = value.Float64
			}
		case balancepackage.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case balancepackage.FieldBadge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field badge", values[i])
			} else if value.Valid {
				_m.Badge = value.String
			}
		case balancepackage.FieldPopular:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field popular", values[i])
			} else if value.Valid {
				_m.Popular = value.Bool
			}
		case balancepackage.FieldForSale:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field for_sale", values[i])
			} else if value.Valid {
				_m.ForSale = value.Bool
			}
		case balancepackage.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case balancepackage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case balancepackage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalancePackage.
// This includes values selected through modifiers, order, etc.
func (_m *BalancePackage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BalancePackage.
// Note that you need to call BalancePackage.Unwrap() before calling this method if this BalancePackage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BalancePackage) Update() *BalancePackageUpdateOne {
	return NewBalancePackageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BalancePackage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BalancePackage) Unwrap() *BalancePackage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalancePackage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BalancePackage) String() string {
	var builder strings.Builder
	builder.WriteString("BalancePackage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("amount_ledger=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountLedger))
	builder.WriteString(", ")
	builder.WriteString("credit_ledger=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditLedger))
	builder.WriteString(", ")
	builder.WriteString("bonus_ledger=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusLedger))
	builder.WriteString(", ")
	builder.WriteString("credit_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditMultiplier))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("badge=")
	builder.WriteString(_m.Badge)
	builder.WriteString(", ")
	builder.WriteString("popular=")
	builder.WriteString(fmt.Sprintf("%v", _m.Popular))
	builder.WriteString(", ")
	builder.WriteString("for_sale=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForSale))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BalancePackages is a parsable slice of BalancePackage.
type BalancePackages []*BalancePackage
