// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancepackage"
)

// BalancePackageCreate is the builder for creating a BalancePackage entity.
type BalancePackageCreate struct {
	config
	mutation *BalancePackageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *BalancePackageCreate) SetCode(v string) *BalancePackageCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *BalancePackageCreate) SetLabel(v string) *BalancePackageCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BalancePackageCreate) SetDescription(v string) *BalancePackageCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableDescription(v *string) *BalancePackageCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetAmountLedger sets the "amount_ledger" field.
func (_c *BalancePackageCreate) SetAmountLedger(v float64) *BalancePackageCreate {
	_c.mutation.SetAmountLedger(v)
	return _c
}

// SetActualCredits sets the "actual_credits" field.
func (_c *BalancePackageCreate) SetActualCredits(v int64) *BalancePackageCreate {
	_c.mutation.SetActualCredits(v)
	return _c
}

// SetNillableActualCredits sets the "actual_credits" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableActualCredits(v *int64) *BalancePackageCreate {
	if v != nil {
		_c.SetActualCredits(*v)
	}
	return _c
}

// SetCreditUnit sets the "credit_unit" field.
func (_c *BalancePackageCreate) SetCreditUnit(v string) *BalancePackageCreate {
	_c.mutation.SetCreditUnit(v)
	return _c
}

// SetNillableCreditUnit sets the "credit_unit" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableCreditUnit(v *string) *BalancePackageCreate {
	if v != nil {
		_c.SetCreditUnit(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *BalancePackageCreate) SetGroupID(v int64) *BalancePackageCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableGroupID(v *int64) *BalancePackageCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetCurrencyOverrides sets the "currency_overrides" field.
func (_c *BalancePackageCreate) SetCurrencyOverrides(v map[string]float64) *BalancePackageCreate {
	_c.mutation.SetCurrencyOverrides(v)
	return _c
}

// SetBadge sets the "badge" field.
func (_c *BalancePackageCreate) SetBadge(v string) *BalancePackageCreate {
	_c.mutation.SetBadge(v)
	return _c
}

// SetNillableBadge sets the "badge" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableBadge(v *string) *BalancePackageCreate {
	if v != nil {
		_c.SetBadge(*v)
	}
	return _c
}

// SetPopular sets the "popular" field.
func (_c *BalancePackageCreate) SetPopular(v bool) *BalancePackageCreate {
	_c.mutation.SetPopular(v)
	return _c
}

// SetNillablePopular sets the "popular" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillablePopular(v *bool) *BalancePackageCreate {
	if v != nil {
		_c.SetPopular(*v)
	}
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *BalancePackageCreate) SetForSale(v bool) *BalancePackageCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableForSale(v *bool) *BalancePackageCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *BalancePackageCreate) SetSortOrder(v int) *BalancePackageCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableSortOrder(v *int) *BalancePackageCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalancePackageCreate) SetCreatedAt(v time.Time) *BalancePackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableCreatedAt(v *time.Time) *BalancePackageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BalancePackageCreate) SetUpdatedAt(v time.Time) *BalancePackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BalancePackageCreate) SetNillableUpdatedAt(v *time.Time) *BalancePackageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BalancePackageMutation object of the builder.
func (_c *BalancePackageCreate) Mutation() *BalancePackageMutation {
	return _c.mutation
}

// Save creates the BalancePackage in the database.
func (_c *BalancePackageCreate) Save(ctx context.Context) (*BalancePackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalancePackageCreate) SaveX(ctx context.Context) *BalancePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalancePackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalancePackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalancePackageCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := balancepackage.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.ActualCredits(); !ok {
		v := balancepackage.DefaultActualCredits
		_c.mutation.SetActualCredits(v)
	}
	if _, ok := _c.mutation.CreditUnit(); !ok {
		v := balancepackage.DefaultCreditUnit
		_c.mutation.SetCreditUnit(v)
	}
	if _, ok := _c.mutation.Badge(); !ok {
		v := balancepackage.DefaultBadge
		_c.mutation.SetBadge(v)
	}
	if _, ok := _c.mutation.Popular(); !ok {
		v := balancepackage.DefaultPopular
		_c.mutation.SetPopular(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := balancepackage.DefaultForSale
		_c.mutation.SetForSale(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := balancepackage.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := balancepackage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := balancepackage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalancePackageCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "BalancePackage.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := balancepackage.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "BalancePackage.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := balancepackage.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "BalancePackage.description"`)}
	}
	if _, ok := _c.mutation.AmountLedger(); !ok {
		return &ValidationError{Name: "amount_ledger", err: errors.New(`ent: missing required field "BalancePackage.amount_ledger"`)}
	}
	if _, ok := _c.mutation.ActualCredits(); !ok {
		return &ValidationError{Name: "actual_credits", err: errors.New(`ent: missing required field "BalancePackage.actual_credits"`)}
	}
	if _, ok := _c.mutation.CreditUnit(); !ok {
		return &ValidationError{Name: "credit_unit", err: errors.New(`ent: missing required field "BalancePackage.credit_unit"`)}
	}
	if v, ok := _c.mutation.CreditUnit(); ok {
		if err := balancepackage.CreditUnitValidator(v); err != nil {
			return &ValidationError{Name: "credit_unit", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.credit_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Badge(); !ok {
		return &ValidationError{Name: "badge", err: errors.New(`ent: missing required field "BalancePackage.badge"`)}
	}
	if v, ok := _c.mutation.Badge(); ok {
		if err := balancepackage.BadgeValidator(v); err != nil {
			return &ValidationError{Name: "badge", err: fmt.Errorf(`ent: validator failed for field "BalancePackage.badge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Popular(); !ok {
		return &ValidationError{Name: "popular", err: errors.New(`ent: missing required field "BalancePackage.popular"`)}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "BalancePackage.for_sale"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "BalancePackage.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BalancePackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BalancePackage.updated_at"`)}
	}
	return nil
}

func (_c *BalancePackageCreate) sqlSave(ctx context.Context) (*BalancePackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalancePackageCreate) createSpec() (*BalancePackage, *sqlgraph.CreateSpec) {
	var (
		_node = &BalancePackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balancepackage.Table, sqlgraph.NewFieldSpec(balancepackage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(balancepackage.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(balancepackage.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(balancepackage.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.AmountLedger(); ok {
		_spec.SetField(balancepackage.FieldAmountLedger, field.TypeFloat64, value)
		_node.AmountLedger = value
	}
	if value, ok := _c.mutation.ActualCredits(); ok {
		_spec.SetField(balancepackage.FieldActualCredits, field.TypeInt64, value)
		_node.ActualCredits = value
	}
	if value, ok := _c.mutation.CreditUnit(); ok {
		_spec.SetField(balancepackage.FieldCreditUnit, field.TypeString, value)
		_node.CreditUnit = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(balancepackage.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.CurrencyOverrides(); ok {
		_spec.SetField(balancepackage.FieldCurrencyOverrides, field.TypeJSON, value)
		_node.CurrencyOverrides = value
	}
	if value, ok := _c.mutation.Badge(); ok {
		_spec.SetField(balancepackage.FieldBadge, field.TypeString, value)
		_node.Badge = value
	}
	if value, ok := _c.mutation.Popular(); ok {
		_spec.SetField(balancepackage.FieldPopular, field.TypeBool, value)
		_node.Popular = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(balancepackage.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(balancepackage.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balancepackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(balancepackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalancePackage.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalancePackageUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *BalancePackageCreate) OnConflict(opts ...sql.ConflictOption) *BalancePackageUpsertOne {
	_c.conflict = opts
	return &BalancePackageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalancePackageCreate) OnConflictColumns(columns ...string) *BalancePackageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalancePackageUpsertOne{
		create: _c,
	}
}

type (
	// BalancePackageUpsertOne is the builder for "upsert"-ing
	//  one BalancePackage node.
	BalancePackageUpsertOne struct {
		create *BalancePackageCreate
	}

	// BalancePackageUpsert is the "OnConflict" setter.
	BalancePackageUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *BalancePackageUpsert) SetCode(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateCode() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldCode)
	return u
}

// SetLabel sets the "label" field.
func (u *BalancePackageUpsert) SetLabel(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateLabel() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldLabel)
	return u
}

// SetDescription sets the "description" field.
func (u *BalancePackageUpsert) SetDescription(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateDescription() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldDescription)
	return u
}

// SetAmountLedger sets the "amount_ledger" field.
func (u *BalancePackageUpsert) SetAmountLedger(v float64) *BalancePackageUpsert {
	u.Set(balancepackage.FieldAmountLedger, v)
	return u
}

// UpdateAmountLedger sets the "amount_ledger" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateAmountLedger() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldAmountLedger)
	return u
}

// AddAmountLedger adds v to the "amount_ledger" field.
func (u *BalancePackageUpsert) AddAmountLedger(v float64) *BalancePackageUpsert {
	u.Add(balancepackage.FieldAmountLedger, v)
	return u
}

// SetActualCredits sets the "actual_credits" field.
func (u *BalancePackageUpsert) SetActualCredits(v int64) *BalancePackageUpsert {
	u.Set(balancepackage.FieldActualCredits, v)
	return u
}

// UpdateActualCredits sets the "actual_credits" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateActualCredits() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldActualCredits)
	return u
}

// AddActualCredits adds v to the "actual_credits" field.
func (u *BalancePackageUpsert) AddActualCredits(v int64) *BalancePackageUpsert {
	u.Add(balancepackage.FieldActualCredits, v)
	return u
}

// SetCreditUnit sets the "credit_unit" field.
func (u *BalancePackageUpsert) SetCreditUnit(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldCreditUnit, v)
	return u
}

// UpdateCreditUnit sets the "credit_unit" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateCreditUnit() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldCreditUnit)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *BalancePackageUpsert) SetGroupID(v int64) *BalancePackageUpsert {
	u.Set(balancepackage.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateGroupID() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *BalancePackageUpsert) AddGroupID(v int64) *BalancePackageUpsert {
	u.Add(balancepackage.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *BalancePackageUpsert) ClearGroupID() *BalancePackageUpsert {
	u.SetNull(balancepackage.FieldGroupID)
	return u
}

// SetCurrencyOverrides sets the "currency_overrides" field.
func (u *BalancePackageUpsert) SetCurrencyOverrides(v map[string]float64) *BalancePackageUpsert {
	u.Set(balancepackage.FieldCurrencyOverrides, v)
	return u
}

// UpdateCurrencyOverrides sets the "currency_overrides" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateCurrencyOverrides() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldCurrencyOverrides)
	return u
}

// ClearCurrencyOverrides clears the value of the "currency_overrides" field.
func (u *BalancePackageUpsert) ClearCurrencyOverrides() *BalancePackageUpsert {
	u.SetNull(balancepackage.FieldCurrencyOverrides)
	return u
}

// SetBadge sets the "badge" field.
func (u *BalancePackageUpsert) SetBadge(v string) *BalancePackageUpsert {
	u.Set(balancepackage.FieldBadge, v)
	return u
}

// UpdateBadge sets the "badge" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateBadge() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldBadge)
	return u
}

// SetPopular sets the "popular" field.
func (u *BalancePackageUpsert) SetPopular(v bool) *BalancePackageUpsert {
	u.Set(balancepackage.FieldPopular, v)
	return u
}

// UpdatePopular sets the "popular" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdatePopular() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldPopular)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *BalancePackageUpsert) SetForSale(v bool) *BalancePackageUpsert {
	u.Set(balancepackage.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateForSale() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldForSale)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *BalancePackageUpsert) SetSortOrder(v int) *BalancePackageUpsert {
	u.Set(balancepackage.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateSortOrder() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalancePackageUpsert) AddSortOrder(v int) *BalancePackageUpsert {
	u.Add(balancepackage.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalancePackageUpsert) SetUpdatedAt(v time.Time) *BalancePackageUpsert {
	u.Set(balancepackage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalancePackageUpsert) UpdateUpdatedAt() *BalancePackageUpsert {
	u.SetExcluded(balancepackage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalancePackageUpsertOne) UpdateNewValues() *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balancepackage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalancePackageUpsertOne) Ignore() *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalancePackageUpsertOne) DoNothing() *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalancePackageCreate.OnConflict
// documentation for more info.
func (u *BalancePackageUpsertOne) Update(set func(*BalancePackageUpsert)) *BalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalancePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *BalancePackageUpsertOne) SetCode(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateCode() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCode()
	})
}

// SetLabel sets the "label" field.
func (u *BalancePackageUpsertOne) SetLabel(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateLabel() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateLabel()
	})
}

// SetDescription sets the "description" field.
func (u *BalancePackageUpsertOne) SetDescription(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateDescription() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateDescription()
	})
}

// SetAmountLedger sets the "amount_ledger" field.
func (u *BalancePackageUpsertOne) SetAmountLedger(v float64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetAmountLedger(v)
	})
}

// AddAmountLedger adds v to the "amount_ledger" field.
func (u *BalancePackageUpsertOne) AddAmountLedger(v float64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddAmountLedger(v)
	})
}

// UpdateAmountLedger sets the "amount_ledger" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateAmountLedger() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateAmountLedger()
	})
}

// SetActualCredits sets the "actual_credits" field.
func (u *BalancePackageUpsertOne) SetActualCredits(v int64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetActualCredits(v)
	})
}

// AddActualCredits adds v to the "actual_credits" field.
func (u *BalancePackageUpsertOne) AddActualCredits(v int64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddActualCredits(v)
	})
}

// UpdateActualCredits sets the "actual_credits" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateActualCredits() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateActualCredits()
	})
}

// SetCreditUnit sets the "credit_unit" field.
func (u *BalancePackageUpsertOne) SetCreditUnit(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCreditUnit(v)
	})
}

// UpdateCreditUnit sets the "credit_unit" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateCreditUnit() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCreditUnit()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BalancePackageUpsertOne) SetGroupID(v int64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *BalancePackageUpsertOne) AddGroupID(v int64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateGroupID() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *BalancePackageUpsertOne) ClearGroupID() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.ClearGroupID()
	})
}

// SetCurrencyOverrides sets the "currency_overrides" field.
func (u *BalancePackageUpsertOne) SetCurrencyOverrides(v map[string]float64) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCurrencyOverrides(v)
	})
}

// UpdateCurrencyOverrides sets the "currency_overrides" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateCurrencyOverrides() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCurrencyOverrides()
	})
}

// ClearCurrencyOverrides clears the value of the "currency_overrides" field.
func (u *BalancePackageUpsertOne) ClearCurrencyOverrides() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.ClearCurrencyOverrides()
	})
}

// SetBadge sets the "badge" field.
func (u *BalancePackageUpsertOne) SetBadge(v string) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetBadge(v)
	})
}

// UpdateBadge sets the "badge" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateBadge() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateBadge()
	})
}

// SetPopular sets the "popular" field.
func (u *BalancePackageUpsertOne) SetPopular(v bool) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetPopular(v)
	})
}

// UpdatePopular sets the "popular" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdatePopular() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdatePopular()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BalancePackageUpsertOne) SetForSale(v bool) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateForSale() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BalancePackageUpsertOne) SetSortOrder(v int) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalancePackageUpsertOne) AddSortOrder(v int) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateSortOrder() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalancePackageUpsertOne) SetUpdatedAt(v time.Time) *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalancePackageUpsertOne) UpdateUpdatedAt() *BalancePackageUpsertOne {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalancePackageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalancePackageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalancePackageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalancePackageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalancePackageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalancePackageCreateBulk is the builder for creating many BalancePackage entities in bulk.
type BalancePackageCreateBulk struct {
	config
	err      error
	builders []*BalancePackageCreate
	conflict []sql.ConflictOption
}

// Save creates the BalancePackage entities in the database.
func (_c *BalancePackageCreateBulk) Save(ctx context.Context) ([]*BalancePackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalancePackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalancePackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalancePackageCreateBulk) SaveX(ctx context.Context) []*BalancePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalancePackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalancePackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalancePackage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalancePackageUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *BalancePackageCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalancePackageUpsertBulk {
	_c.conflict = opts
	return &BalancePackageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalancePackageCreateBulk) OnConflictColumns(columns ...string) *BalancePackageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalancePackageUpsertBulk{
		create: _c,
	}
}

// BalancePackageUpsertBulk is the builder for "upsert"-ing
// a bulk of BalancePackage nodes.
type BalancePackageUpsertBulk struct {
	create *BalancePackageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalancePackageUpsertBulk) UpdateNewValues() *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balancepackage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalancePackage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalancePackageUpsertBulk) Ignore() *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalancePackageUpsertBulk) DoNothing() *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalancePackageCreateBulk.OnConflict
// documentation for more info.
func (u *BalancePackageUpsertBulk) Update(set func(*BalancePackageUpsert)) *BalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalancePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *BalancePackageUpsertBulk) SetCode(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateCode() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCode()
	})
}

// SetLabel sets the "label" field.
func (u *BalancePackageUpsertBulk) SetLabel(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateLabel() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateLabel()
	})
}

// SetDescription sets the "description" field.
func (u *BalancePackageUpsertBulk) SetDescription(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateDescription() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateDescription()
	})
}

// SetAmountLedger sets the "amount_ledger" field.
func (u *BalancePackageUpsertBulk) SetAmountLedger(v float64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetAmountLedger(v)
	})
}

// AddAmountLedger adds v to the "amount_ledger" field.
func (u *BalancePackageUpsertBulk) AddAmountLedger(v float64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddAmountLedger(v)
	})
}

// UpdateAmountLedger sets the "amount_ledger" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateAmountLedger() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateAmountLedger()
	})
}

// SetActualCredits sets the "actual_credits" field.
func (u *BalancePackageUpsertBulk) SetActualCredits(v int64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetActualCredits(v)
	})
}

// AddActualCredits adds v to the "actual_credits" field.
func (u *BalancePackageUpsertBulk) AddActualCredits(v int64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddActualCredits(v)
	})
}

// UpdateActualCredits sets the "actual_credits" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateActualCredits() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateActualCredits()
	})
}

// SetCreditUnit sets the "credit_unit" field.
func (u *BalancePackageUpsertBulk) SetCreditUnit(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCreditUnit(v)
	})
}

// UpdateCreditUnit sets the "credit_unit" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateCreditUnit() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCreditUnit()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BalancePackageUpsertBulk) SetGroupID(v int64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *BalancePackageUpsertBulk) AddGroupID(v int64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateGroupID() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *BalancePackageUpsertBulk) ClearGroupID() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.ClearGroupID()
	})
}

// SetCurrencyOverrides sets the "currency_overrides" field.
func (u *BalancePackageUpsertBulk) SetCurrencyOverrides(v map[string]float64) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetCurrencyOverrides(v)
	})
}

// UpdateCurrencyOverrides sets the "currency_overrides" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateCurrencyOverrides() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateCurrencyOverrides()
	})
}

// ClearCurrencyOverrides clears the value of the "currency_overrides" field.
func (u *BalancePackageUpsertBulk) ClearCurrencyOverrides() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.ClearCurrencyOverrides()
	})
}

// SetBadge sets the "badge" field.
func (u *BalancePackageUpsertBulk) SetBadge(v string) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetBadge(v)
	})
}

// UpdateBadge sets the "badge" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateBadge() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateBadge()
	})
}

// SetPopular sets the "popular" field.
func (u *BalancePackageUpsertBulk) SetPopular(v bool) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetPopular(v)
	})
}

// UpdatePopular sets the "popular" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdatePopular() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdatePopular()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BalancePackageUpsertBulk) SetForSale(v bool) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateForSale() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BalancePackageUpsertBulk) SetSortOrder(v int) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalancePackageUpsertBulk) AddSortOrder(v int) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateSortOrder() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalancePackageUpsertBulk) SetUpdatedAt(v time.Time) *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalancePackageUpsertBulk) UpdateUpdatedAt() *BalancePackageUpsertBulk {
	return u.Update(func(s *BalancePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalancePackageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalancePackageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalancePackageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalancePackageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
