// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/catalogrevision"
)

// CatalogRevision is the model entity for the CatalogRevision schema.
type CatalogRevision struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int64 `json:"revision,omitempty"`
	// SyncRunID holds the value of the "sync_run_id" field.
	SyncRunID int64 `json:"sync_run_id,omitempty"`
	// NormalizedHash holds the value of the "normalized_hash" field.
	NormalizedHash string `json:"normalized_hash,omitempty"`
	// NormalizerVersion holds the value of the "normalizer_version" field.
	NormalizerVersion string `json:"normalizer_version,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// ModelCount holds the value of the "model_count" field.
	ModelCount int `json:"model_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ValidatedAt holds the value of the "validated_at" field.
	ValidatedAt *time.Time `json:"validated_at,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt  *time.Time `json:"published_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CatalogRevision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case catalogrevision.FieldID, catalogrevision.FieldRevision, catalogrevision.FieldSyncRunID, catalogrevision.FieldModelCount:
			values[i] = new(sql.NullInt64)
		case catalogrevision.FieldNormalizedHash, catalogrevision.FieldNormalizerVersion, catalogrevision.FieldState:
			values[i] = new(sql.NullString)
		case catalogrevision.FieldCreatedAt, catalogrevision.FieldValidatedAt, catalogrevision.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CatalogRevision fields.
func (_m *CatalogRevision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case catalogrevision.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case catalogrevision.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case catalogrevision.FieldSyncRunID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_run_id", values[i])
			} else if value.Valid {
				_m.SyncRunID = value.Int64
			}
		case catalogrevision.FieldNormalizedHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_hash", values[i])
			} else if value.Valid {
				_m.NormalizedHash = value.String
			}
		case catalogrevision.FieldNormalizerVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalizer_version", values[i])
			} else if value.Valid {
				_m.NormalizerVersion = value.String
			}
		case catalogrevision.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case catalogrevision.FieldModelCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_count", values[i])
			} else if value.Valid {
				_m.ModelCount = int(value.Int64)
			}
		case catalogrevision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case catalogrevision.FieldValidatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field validated_at", values[i])
			} else if value.Valid {
				_m.ValidatedAt = new(time.Time)
				*_m.ValidatedAt = value.Time
			}
		case catalogrevision.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CatalogRevision.
// This includes values selected through modifiers, order, etc.
func (_m *CatalogRevision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CatalogRevision.
// Note that you need to call CatalogRevision.Unwrap() before calling this method if this CatalogRevision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CatalogRevision) Update() *CatalogRevisionUpdateOne {
	return NewCatalogRevisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CatalogRevision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CatalogRevision) Unwrap() *CatalogRevision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CatalogRevision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CatalogRevision) String() string {
	var builder strings.Builder
	builder.WriteString("CatalogRevision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("sync_run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncRunID))
	builder.WriteString(", ")
	builder.WriteString("normalized_hash=")
	builder.WriteString(_m.NormalizedHash)
	builder.WriteString(", ")
	builder.WriteString("normalizer_version=")
	builder.WriteString(_m.NormalizerVersion)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("model_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidatedAt; v != nil {
		builder.WriteString("validated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CatalogRevisions is a parsable slice of CatalogRevision.
type CatalogRevisions []*CatalogRevision
