// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/catalogmodelrevision"
)

// CatalogModelRevision is the model entity for the CatalogModelRevision schema.
type CatalogModelRevision struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CatalogRevisionID holds the value of the "catalog_revision_id" field.
	CatalogRevisionID int64 `json:"catalog_revision_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID int64 `json:"model_id,omitempty"`
	// SourceState holds the value of the "source_state" field.
	SourceState string `json:"source_state,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities map[string]interface{} `json:"capabilities,omitempty"`
	// ContextWindow holds the value of the "context_window" field.
	ContextWindow *int64 `json:"context_window,omitempty"`
	// MaxOutputTokens holds the value of the "max_output_tokens" field.
	MaxOutputTokens *int64 `json:"max_output_tokens,omitempty"`
	// PricingSchemaVersion holds the value of the "pricing_schema_version" field.
	PricingSchemaVersion int `json:"pricing_schema_version,omitempty"`
	// PricingJSON holds the value of the "pricing_json" field.
	PricingJSON map[string]interface{} `json:"pricing_json,omitempty"`
	// PricingValid holds the value of the "pricing_valid" field.
	PricingValid bool `json:"pricing_valid,omitempty"`
	// PricingSource holds the value of the "pricing_source" field.
	PricingSource *string `json:"pricing_source,omitempty"`
	// SourceMetadata holds the value of the "source_metadata" field.
	SourceMetadata map[string]interface{} `json:"source_metadata,omitempty"`
	// SourceHash holds the value of the "source_hash" field.
	SourceHash string `json:"source_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CatalogModelRevision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case catalogmodelrevision.FieldCapabilities, catalogmodelrevision.FieldPricingJSON, catalogmodelrevision.FieldSourceMetadata:
			values[i] = new([]byte)
		case catalogmodelrevision.FieldPricingValid:
			values[i] = new(sql.NullBool)
		case catalogmodelrevision.FieldID, catalogmodelrevision.FieldCatalogRevisionID, catalogmodelrevision.FieldModelID, catalogmodelrevision.FieldContextWindow, catalogmodelrevision.FieldMaxOutputTokens, catalogmodelrevision.FieldPricingSchemaVersion:
			values[i] = new(sql.NullInt64)
		case catalogmodelrevision.FieldSourceState, catalogmodelrevision.FieldProvider, catalogmodelrevision.FieldPlatform, catalogmodelrevision.FieldMode, catalogmodelrevision.FieldPricingSource, catalogmodelrevision.FieldSourceHash:
			values[i] = new(sql.NullString)
		case catalogmodelrevision.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CatalogModelRevision fields.
func (_m *CatalogModelRevision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case catalogmodelrevision.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case catalogmodelrevision.FieldCatalogRevisionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field catalog_revision_id", values[i])
			} else if value.Valid {
				_m.CatalogRevisionID = value.Int64
			}
		case catalogmodelrevision.FieldModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.Int64
			}
		case catalogmodelrevision.FieldSourceState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_state", values[i])
			} else if value.Valid {
				_m.SourceState = value.String
			}
		case catalogmodelrevision.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case catalogmodelrevision.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case catalogmodelrevision.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case catalogmodelrevision.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case catalogmodelrevision.FieldContextWindow:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field context_window", values[i])
			} else if value.Valid {
				_m.ContextWindow = new(int64)
				*_m.ContextWindow = value.Int64
			}
		case catalogmodelrevision.FieldMaxOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_output_tokens", values[i])
			} else if value.Valid {
				_m.MaxOutputTokens = new(int64)
				*_m.MaxOutputTokens = value.Int64
			}
		case catalogmodelrevision.FieldPricingSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_schema_version", values[i])
			} else if value.Valid {
				_m.PricingSchemaVersion = int(value.Int64)
			}
		case catalogmodelrevision.FieldPricingJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PricingJSON); err != nil {
					return fmt.Errorf("unmarshal field pricing_json: %w", err)
				}
			}
		case catalogmodelrevision.FieldPricingValid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_valid", values[i])
			} else if value.Valid {
				_m.PricingValid = value.Bool
			}
		case catalogmodelrevision.FieldPricingSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_source", values[i])
			} else if value.Valid {
				_m.PricingSource = new(string)
				*_m.PricingSource = value.String
			}
		case catalogmodelrevision.FieldSourceMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field source_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SourceMetadata); err != nil {
					return fmt.Errorf("unmarshal field source_metadata: %w", err)
				}
			}
		case catalogmodelrevision.FieldSourceHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_hash", values[i])
			} else if value.Valid {
				_m.SourceHash = value.String
			}
		case catalogmodelrevision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CatalogModelRevision.
// This includes values selected through modifiers, order, etc.
func (_m *CatalogModelRevision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CatalogModelRevision.
// Note that you need to call CatalogModelRevision.Unwrap() before calling this method if this CatalogModelRevision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CatalogModelRevision) Update() *CatalogModelRevisionUpdateOne {
	return NewCatalogModelRevisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CatalogModelRevision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CatalogModelRevision) Unwrap() *CatalogModelRevision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CatalogModelRevision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CatalogModelRevision) String() string {
	var builder strings.Builder
	builder.WriteString("CatalogModelRevision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("catalog_revision_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CatalogRevisionID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelID))
	builder.WriteString(", ")
	builder.WriteString("source_state=")
	builder.WriteString(_m.SourceState)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	if v := _m.ContextWindow; v != nil {
		builder.WriteString("context_window=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxOutputTokens; v != nil {
		builder.WriteString("max_output_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("pricing_schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricingSchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("pricing_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricingJSON))
	builder.WriteString(", ")
	builder.WriteString("pricing_valid=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricingValid))
	builder.WriteString(", ")
	if v := _m.PricingSource; v != nil {
		builder.WriteString("pricing_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("source_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceMetadata))
	builder.WriteString(", ")
	builder.WriteString("source_hash=")
	builder.WriteString(_m.SourceHash)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CatalogModelRevisions is a parsable slice of CatalogModelRevision.
type CatalogModelRevisions []*CatalogModelRevision
