// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/catalogmodelalias"
)

// CatalogModelAlias is the model entity for the CatalogModelAlias schema.
type CatalogModelAlias struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AliasNormalized holds the value of the "alias_normalized" field.
	AliasNormalized string `json:"alias_normalized,omitempty"`
	// PlatformScope holds the value of the "platform_scope" field.
	PlatformScope string `json:"platform_scope,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID int64 `json:"model_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// IntroducedRevisionID holds the value of the "introduced_revision_id" field.
	IntroducedRevisionID *int64 `json:"introduced_revision_id,omitempty"`
	// RetiredRevisionID holds the value of the "retired_revision_id" field.
	RetiredRevisionID *int64 `json:"retired_revision_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CatalogModelAlias) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case catalogmodelalias.FieldID, catalogmodelalias.FieldModelID, catalogmodelalias.FieldIntroducedRevisionID, catalogmodelalias.FieldRetiredRevisionID:
			values[i] = new(sql.NullInt64)
		case catalogmodelalias.FieldAliasNormalized, catalogmodelalias.FieldPlatformScope, catalogmodelalias.FieldSource, catalogmodelalias.FieldState:
			values[i] = new(sql.NullString)
		case catalogmodelalias.FieldCreatedAt, catalogmodelalias.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CatalogModelAlias fields.
func (_m *CatalogModelAlias) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case catalogmodelalias.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case catalogmodelalias.FieldAliasNormalized:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias_normalized", values[i])
			} else if value.Valid {
				_m.AliasNormalized = value.String
			}
		case catalogmodelalias.FieldPlatformScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_scope", values[i])
			} else if value.Valid {
				_m.PlatformScope = value.String
			}
		case catalogmodelalias.FieldModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.Int64
			}
		case catalogmodelalias.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case catalogmodelalias.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case catalogmodelalias.FieldIntroducedRevisionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field introduced_revision_id", values[i])
			} else if value.Valid {
				_m.IntroducedRevisionID = new(int64)
				*_m.IntroducedRevisionID = value.Int64
			}
		case catalogmodelalias.FieldRetiredRevisionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retired_revision_id", values[i])
			} else if value.Valid {
				_m.RetiredRevisionID = new(int64)
				*_m.RetiredRevisionID = value.Int64
			}
		case catalogmodelalias.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case catalogmodelalias.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CatalogModelAlias.
// This includes values selected through modifiers, order, etc.
func (_m *CatalogModelAlias) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CatalogModelAlias.
// Note that you need to call CatalogModelAlias.Unwrap() before calling this method if this CatalogModelAlias
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CatalogModelAlias) Update() *CatalogModelAliasUpdateOne {
	return NewCatalogModelAliasClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CatalogModelAlias entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CatalogModelAlias) Unwrap() *CatalogModelAlias {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CatalogModelAlias is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CatalogModelAlias) String() string {
	var builder strings.Builder
	builder.WriteString("CatalogModelAlias(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("alias_normalized=")
	builder.WriteString(_m.AliasNormalized)
	builder.WriteString(", ")
	builder.WriteString("platform_scope=")
	builder.WriteString(_m.PlatformScope)
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelID))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	if v := _m.IntroducedRevisionID; v != nil {
		builder.WriteString("introduced_revision_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RetiredRevisionID; v != nil {
		builder.WriteString("retired_revision_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CatalogModelAliasSlice is a parsable slice of CatalogModelAlias.
type CatalogModelAliasSlice []*CatalogModelAlias
