// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catalogmodelalias"
)

// CatalogModelAliasCreate is the builder for creating a CatalogModelAlias entity.
type CatalogModelAliasCreate struct {
	config
	mutation *CatalogModelAliasMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAliasNormalized sets the "alias_normalized" field.
func (_c *CatalogModelAliasCreate) SetAliasNormalized(v string) *CatalogModelAliasCreate {
	_c.mutation.SetAliasNormalized(v)
	return _c
}

// SetPlatformScope sets the "platform_scope" field.
func (_c *CatalogModelAliasCreate) SetPlatformScope(v string) *CatalogModelAliasCreate {
	_c.mutation.SetPlatformScope(v)
	return _c
}

// SetNillablePlatformScope sets the "platform_scope" field if the given value is not nil.
func (_c *CatalogModelAliasCreate) SetNillablePlatformScope(v *string) *CatalogModelAliasCreate {
	if v != nil {
		_c.SetPlatformScope(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *CatalogModelAliasCreate) SetModelID(v int64) *CatalogModelAliasCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *CatalogModelAliasCreate) SetSource(v string) *CatalogModelAliasCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetState sets the "state" field.
func (_c *CatalogModelAliasCreate) SetState(v string) *CatalogModelAliasCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetIntroducedRevisionID sets the "introduced_revision_id" field.
func (_c *CatalogModelAliasCreate) SetIntroducedRevisionID(v int64) *CatalogModelAliasCreate {
	_c.mutation.SetIntroducedRevisionID(v)
	return _c
}

// SetNillableIntroducedRevisionID sets the "introduced_revision_id" field if the given value is not nil.
func (_c *CatalogModelAliasCreate) SetNillableIntroducedRevisionID(v *int64) *CatalogModelAliasCreate {
	if v != nil {
		_c.SetIntroducedRevisionID(*v)
	}
	return _c
}

// SetRetiredRevisionID sets the "retired_revision_id" field.
func (_c *CatalogModelAliasCreate) SetRetiredRevisionID(v int64) *CatalogModelAliasCreate {
	_c.mutation.SetRetiredRevisionID(v)
	return _c
}

// SetNillableRetiredRevisionID sets the "retired_revision_id" field if the given value is not nil.
func (_c *CatalogModelAliasCreate) SetNillableRetiredRevisionID(v *int64) *CatalogModelAliasCreate {
	if v != nil {
		_c.SetRetiredRevisionID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CatalogModelAliasCreate) SetCreatedAt(v time.Time) *CatalogModelAliasCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CatalogModelAliasCreate) SetNillableCreatedAt(v *time.Time) *CatalogModelAliasCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CatalogModelAliasCreate) SetUpdatedAt(v time.Time) *CatalogModelAliasCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CatalogModelAliasCreate) SetNillableUpdatedAt(v *time.Time) *CatalogModelAliasCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CatalogModelAliasMutation object of the builder.
func (_c *CatalogModelAliasCreate) Mutation() *CatalogModelAliasMutation {
	return _c.mutation
}

// Save creates the CatalogModelAlias in the database.
func (_c *CatalogModelAliasCreate) Save(ctx context.Context) (*CatalogModelAlias, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CatalogModelAliasCreate) SaveX(ctx context.Context) *CatalogModelAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CatalogModelAliasCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CatalogModelAliasCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CatalogModelAliasCreate) defaults() {
	if _, ok := _c.mutation.PlatformScope(); !ok {
		v := catalogmodelalias.DefaultPlatformScope
		_c.mutation.SetPlatformScope(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := catalogmodelalias.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := catalogmodelalias.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CatalogModelAliasCreate) check() error {
	if _, ok := _c.mutation.AliasNormalized(); !ok {
		return &ValidationError{Name: "alias_normalized", err: errors.New(`ent: missing required field "CatalogModelAlias.alias_normalized"`)}
	}
	if _, ok := _c.mutation.PlatformScope(); !ok {
		return &ValidationError{Name: "platform_scope", err: errors.New(`ent: missing required field "CatalogModelAlias.platform_scope"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "CatalogModelAlias.model_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "CatalogModelAlias.source"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "CatalogModelAlias.state"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CatalogModelAlias.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CatalogModelAlias.updated_at"`)}
	}
	return nil
}

func (_c *CatalogModelAliasCreate) sqlSave(ctx context.Context) (*CatalogModelAlias, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CatalogModelAliasCreate) createSpec() (*CatalogModelAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &CatalogModelAlias{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(catalogmodelalias.Table, sqlgraph.NewFieldSpec(catalogmodelalias.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AliasNormalized(); ok {
		_spec.SetField(catalogmodelalias.FieldAliasNormalized, field.TypeString, value)
		_node.AliasNormalized = value
	}
	if value, ok := _c.mutation.PlatformScope(); ok {
		_spec.SetField(catalogmodelalias.FieldPlatformScope, field.TypeString, value)
		_node.PlatformScope = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(catalogmodelalias.FieldModelID, field.TypeInt64, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(catalogmodelalias.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(catalogmodelalias.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.IntroducedRevisionID(); ok {
		_spec.SetField(catalogmodelalias.FieldIntroducedRevisionID, field.TypeInt64, value)
		_node.IntroducedRevisionID = &value
	}
	if value, ok := _c.mutation.RetiredRevisionID(); ok {
		_spec.SetField(catalogmodelalias.FieldRetiredRevisionID, field.TypeInt64, value)
		_node.RetiredRevisionID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(catalogmodelalias.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(catalogmodelalias.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CatalogModelAlias.Create().
//		SetAliasNormalized(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CatalogModelAliasUpsert) {
//			SetAliasNormalized(v+v).
//		}).
//		Exec(ctx)
func (_c *CatalogModelAliasCreate) OnConflict(opts ...sql.ConflictOption) *CatalogModelAliasUpsertOne {
	_c.conflict = opts
	return &CatalogModelAliasUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CatalogModelAlias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CatalogModelAliasCreate) OnConflictColumns(columns ...string) *CatalogModelAliasUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CatalogModelAliasUpsertOne{
		create: _c,
	}
}

type (
	// CatalogModelAliasUpsertOne is the builder for "upsert"-ing
	//  one CatalogModelAlias node.
	CatalogModelAliasUpsertOne struct {
		create *CatalogModelAliasCreate
	}

	// CatalogModelAliasUpsert is the "OnConflict" setter.
	CatalogModelAliasUpsert struct {
		*sql.UpdateSet
	}
)

// SetAliasNormalized sets the "alias_normalized" field.
func (u *CatalogModelAliasUpsert) SetAliasNormalized(v string) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldAliasNormalized, v)
	return u
}

// UpdateAliasNormalized sets the "alias_normalized" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateAliasNormalized() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldAliasNormalized)
	return u
}

// SetPlatformScope sets the "platform_scope" field.
func (u *CatalogModelAliasUpsert) SetPlatformScope(v string) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldPlatformScope, v)
	return u
}

// UpdatePlatformScope sets the "platform_scope" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdatePlatformScope() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldPlatformScope)
	return u
}

// SetModelID sets the "model_id" field.
func (u *CatalogModelAliasUpsert) SetModelID(v int64) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateModelID() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldModelID)
	return u
}

// AddModelID adds v to the "model_id" field.
func (u *CatalogModelAliasUpsert) AddModelID(v int64) *CatalogModelAliasUpsert {
	u.Add(catalogmodelalias.FieldModelID, v)
	return u
}

// SetSource sets the "source" field.
func (u *CatalogModelAliasUpsert) SetSource(v string) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateSource() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldSource)
	return u
}

// SetState sets the "state" field.
func (u *CatalogModelAliasUpsert) SetState(v string) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateState() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldState)
	return u
}

// SetIntroducedRevisionID sets the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsert) SetIntroducedRevisionID(v int64) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldIntroducedRevisionID, v)
	return u
}

// UpdateIntroducedRevisionID sets the "introduced_revision_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateIntroducedRevisionID() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldIntroducedRevisionID)
	return u
}

// AddIntroducedRevisionID adds v to the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsert) AddIntroducedRevisionID(v int64) *CatalogModelAliasUpsert {
	u.Add(catalogmodelalias.FieldIntroducedRevisionID, v)
	return u
}

// ClearIntroducedRevisionID clears the value of the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsert) ClearIntroducedRevisionID() *CatalogModelAliasUpsert {
	u.SetNull(catalogmodelalias.FieldIntroducedRevisionID)
	return u
}

// SetRetiredRevisionID sets the "retired_revision_id" field.
func (u *CatalogModelAliasUpsert) SetRetiredRevisionID(v int64) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldRetiredRevisionID, v)
	return u
}

// UpdateRetiredRevisionID sets the "retired_revision_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateRetiredRevisionID() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldRetiredRevisionID)
	return u
}

// AddRetiredRevisionID adds v to the "retired_revision_id" field.
func (u *CatalogModelAliasUpsert) AddRetiredRevisionID(v int64) *CatalogModelAliasUpsert {
	u.Add(catalogmodelalias.FieldRetiredRevisionID, v)
	return u
}

// ClearRetiredRevisionID clears the value of the "retired_revision_id" field.
func (u *CatalogModelAliasUpsert) ClearRetiredRevisionID() *CatalogModelAliasUpsert {
	u.SetNull(catalogmodelalias.FieldRetiredRevisionID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CatalogModelAliasUpsert) SetCreatedAt(v time.Time) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateCreatedAt() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CatalogModelAliasUpsert) SetUpdatedAt(v time.Time) *CatalogModelAliasUpsert {
	u.Set(catalogmodelalias.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CatalogModelAliasUpsert) UpdateUpdatedAt() *CatalogModelAliasUpsert {
	u.SetExcluded(catalogmodelalias.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CatalogModelAlias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CatalogModelAliasUpsertOne) UpdateNewValues() *CatalogModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CatalogModelAlias.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CatalogModelAliasUpsertOne) Ignore() *CatalogModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CatalogModelAliasUpsertOne) DoNothing() *CatalogModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CatalogModelAliasCreate.OnConflict
// documentation for more info.
func (u *CatalogModelAliasUpsertOne) Update(set func(*CatalogModelAliasUpsert)) *CatalogModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CatalogModelAliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetAliasNormalized sets the "alias_normalized" field.
func (u *CatalogModelAliasUpsertOne) SetAliasNormalized(v string) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetAliasNormalized(v)
	})
}

// UpdateAliasNormalized sets the "alias_normalized" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateAliasNormalized() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateAliasNormalized()
	})
}

// SetPlatformScope sets the "platform_scope" field.
func (u *CatalogModelAliasUpsertOne) SetPlatformScope(v string) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetPlatformScope(v)
	})
}

// UpdatePlatformScope sets the "platform_scope" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdatePlatformScope() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdatePlatformScope()
	})
}

// SetModelID sets the "model_id" field.
func (u *CatalogModelAliasUpsertOne) SetModelID(v int64) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetModelID(v)
	})
}

// AddModelID adds v to the "model_id" field.
func (u *CatalogModelAliasUpsertOne) AddModelID(v int64) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.AddModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateModelID() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateModelID()
	})
}

// SetSource sets the "source" field.
func (u *CatalogModelAliasUpsertOne) SetSource(v string) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateSource() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateSource()
	})
}

// SetState sets the "state" field.
func (u *CatalogModelAliasUpsertOne) SetState(v string) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateState() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateState()
	})
}

// SetIntroducedRevisionID sets the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsertOne) SetIntroducedRevisionID(v int64) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetIntroducedRevisionID(v)
	})
}

// AddIntroducedRevisionID adds v to the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsertOne) AddIntroducedRevisionID(v int64) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.AddIntroducedRevisionID(v)
	})
}

// UpdateIntroducedRevisionID sets the "introduced_revision_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateIntroducedRevisionID() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateIntroducedRevisionID()
	})
}

// ClearIntroducedRevisionID clears the value of the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsertOne) ClearIntroducedRevisionID() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.ClearIntroducedRevisionID()
	})
}

// SetRetiredRevisionID sets the "retired_revision_id" field.
func (u *CatalogModelAliasUpsertOne) SetRetiredRevisionID(v int64) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetRetiredRevisionID(v)
	})
}

// AddRetiredRevisionID adds v to the "retired_revision_id" field.
func (u *CatalogModelAliasUpsertOne) AddRetiredRevisionID(v int64) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.AddRetiredRevisionID(v)
	})
}

// UpdateRetiredRevisionID sets the "retired_revision_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateRetiredRevisionID() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateRetiredRevisionID()
	})
}

// ClearRetiredRevisionID clears the value of the "retired_revision_id" field.
func (u *CatalogModelAliasUpsertOne) ClearRetiredRevisionID() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.ClearRetiredRevisionID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CatalogModelAliasUpsertOne) SetCreatedAt(v time.Time) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateCreatedAt() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CatalogModelAliasUpsertOne) SetUpdatedAt(v time.Time) *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertOne) UpdateUpdatedAt() *CatalogModelAliasUpsertOne {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CatalogModelAliasUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CatalogModelAliasCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CatalogModelAliasUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CatalogModelAliasUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CatalogModelAliasUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CatalogModelAliasCreateBulk is the builder for creating many CatalogModelAlias entities in bulk.
type CatalogModelAliasCreateBulk struct {
	config
	err      error
	builders []*CatalogModelAliasCreate
	conflict []sql.ConflictOption
}

// Save creates the CatalogModelAlias entities in the database.
func (_c *CatalogModelAliasCreateBulk) Save(ctx context.Context) ([]*CatalogModelAlias, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CatalogModelAlias, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CatalogModelAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CatalogModelAliasCreateBulk) SaveX(ctx context.Context) []*CatalogModelAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CatalogModelAliasCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CatalogModelAliasCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CatalogModelAlias.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CatalogModelAliasUpsert) {
//			SetAliasNormalized(v+v).
//		}).
//		Exec(ctx)
func (_c *CatalogModelAliasCreateBulk) OnConflict(opts ...sql.ConflictOption) *CatalogModelAliasUpsertBulk {
	_c.conflict = opts
	return &CatalogModelAliasUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CatalogModelAlias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CatalogModelAliasCreateBulk) OnConflictColumns(columns ...string) *CatalogModelAliasUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CatalogModelAliasUpsertBulk{
		create: _c,
	}
}

// CatalogModelAliasUpsertBulk is the builder for "upsert"-ing
// a bulk of CatalogModelAlias nodes.
type CatalogModelAliasUpsertBulk struct {
	create *CatalogModelAliasCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CatalogModelAlias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CatalogModelAliasUpsertBulk) UpdateNewValues() *CatalogModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CatalogModelAlias.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CatalogModelAliasUpsertBulk) Ignore() *CatalogModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CatalogModelAliasUpsertBulk) DoNothing() *CatalogModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CatalogModelAliasCreateBulk.OnConflict
// documentation for more info.
func (u *CatalogModelAliasUpsertBulk) Update(set func(*CatalogModelAliasUpsert)) *CatalogModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CatalogModelAliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetAliasNormalized sets the "alias_normalized" field.
func (u *CatalogModelAliasUpsertBulk) SetAliasNormalized(v string) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetAliasNormalized(v)
	})
}

// UpdateAliasNormalized sets the "alias_normalized" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateAliasNormalized() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateAliasNormalized()
	})
}

// SetPlatformScope sets the "platform_scope" field.
func (u *CatalogModelAliasUpsertBulk) SetPlatformScope(v string) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetPlatformScope(v)
	})
}

// UpdatePlatformScope sets the "platform_scope" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdatePlatformScope() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdatePlatformScope()
	})
}

// SetModelID sets the "model_id" field.
func (u *CatalogModelAliasUpsertBulk) SetModelID(v int64) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetModelID(v)
	})
}

// AddModelID adds v to the "model_id" field.
func (u *CatalogModelAliasUpsertBulk) AddModelID(v int64) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.AddModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateModelID() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateModelID()
	})
}

// SetSource sets the "source" field.
func (u *CatalogModelAliasUpsertBulk) SetSource(v string) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateSource() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateSource()
	})
}

// SetState sets the "state" field.
func (u *CatalogModelAliasUpsertBulk) SetState(v string) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateState() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateState()
	})
}

// SetIntroducedRevisionID sets the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsertBulk) SetIntroducedRevisionID(v int64) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetIntroducedRevisionID(v)
	})
}

// AddIntroducedRevisionID adds v to the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsertBulk) AddIntroducedRevisionID(v int64) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.AddIntroducedRevisionID(v)
	})
}

// UpdateIntroducedRevisionID sets the "introduced_revision_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateIntroducedRevisionID() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateIntroducedRevisionID()
	})
}

// ClearIntroducedRevisionID clears the value of the "introduced_revision_id" field.
func (u *CatalogModelAliasUpsertBulk) ClearIntroducedRevisionID() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.ClearIntroducedRevisionID()
	})
}

// SetRetiredRevisionID sets the "retired_revision_id" field.
func (u *CatalogModelAliasUpsertBulk) SetRetiredRevisionID(v int64) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetRetiredRevisionID(v)
	})
}

// AddRetiredRevisionID adds v to the "retired_revision_id" field.
func (u *CatalogModelAliasUpsertBulk) AddRetiredRevisionID(v int64) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.AddRetiredRevisionID(v)
	})
}

// UpdateRetiredRevisionID sets the "retired_revision_id" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateRetiredRevisionID() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateRetiredRevisionID()
	})
}

// ClearRetiredRevisionID clears the value of the "retired_revision_id" field.
func (u *CatalogModelAliasUpsertBulk) ClearRetiredRevisionID() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.ClearRetiredRevisionID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CatalogModelAliasUpsertBulk) SetCreatedAt(v time.Time) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateCreatedAt() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CatalogModelAliasUpsertBulk) SetUpdatedAt(v time.Time) *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CatalogModelAliasUpsertBulk) UpdateUpdatedAt() *CatalogModelAliasUpsertBulk {
	return u.Update(func(s *CatalogModelAliasUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CatalogModelAliasUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CatalogModelAliasCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CatalogModelAliasCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CatalogModelAliasUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
