// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catalogsyncrun"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CatalogSyncRunUpdate is the builder for updating CatalogSyncRun entities.
type CatalogSyncRunUpdate struct {
	config
	hooks    []Hook
	mutation *CatalogSyncRunMutation
}

// Where appends a list predicates to the CatalogSyncRunUpdate builder.
func (_u *CatalogSyncRunUpdate) Where(ps ...predicate.CatalogSyncRun) *CatalogSyncRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceSet sets the "source_set" field.
func (_u *CatalogSyncRunUpdate) SetSourceSet(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetSourceSet(v)
	return _u
}

// SetNillableSourceSet sets the "source_set" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableSourceSet(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetSourceSet(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *CatalogSyncRunUpdate) SetTrigger(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableTrigger(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *CatalogSyncRunUpdate) SetActorUserID(v int64) *CatalogSyncRunUpdate {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableActorUserID(v *int64) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *CatalogSyncRunUpdate) AddActorUserID(v int64) *CatalogSyncRunUpdate {
	_u.mutation.AddActorUserID(v)
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *CatalogSyncRunUpdate) ClearActorUserID() *CatalogSyncRunUpdate {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetUpstreamVersion sets the "upstream_version" field.
func (_u *CatalogSyncRunUpdate) SetUpstreamVersion(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetUpstreamVersion(v)
	return _u
}

// SetNillableUpstreamVersion sets the "upstream_version" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableUpstreamVersion(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetUpstreamVersion(*v)
	}
	return _u
}

// ClearUpstreamVersion clears the value of the "upstream_version" field.
func (_u *CatalogSyncRunUpdate) ClearUpstreamVersion() *CatalogSyncRunUpdate {
	_u.mutation.ClearUpstreamVersion()
	return _u
}

// SetUpstreamEtag sets the "upstream_etag" field.
func (_u *CatalogSyncRunUpdate) SetUpstreamEtag(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetUpstreamEtag(v)
	return _u
}

// SetNillableUpstreamEtag sets the "upstream_etag" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableUpstreamEtag(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetUpstreamEtag(*v)
	}
	return _u
}

// ClearUpstreamEtag clears the value of the "upstream_etag" field.
func (_u *CatalogSyncRunUpdate) ClearUpstreamEtag() *CatalogSyncRunUpdate {
	_u.mutation.ClearUpstreamEtag()
	return _u
}

// SetUpstreamHash sets the "upstream_hash" field.
func (_u *CatalogSyncRunUpdate) SetUpstreamHash(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetUpstreamHash(v)
	return _u
}

// SetNillableUpstreamHash sets the "upstream_hash" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableUpstreamHash(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetUpstreamHash(*v)
	}
	return _u
}

// ClearUpstreamHash clears the value of the "upstream_hash" field.
func (_u *CatalogSyncRunUpdate) ClearUpstreamHash() *CatalogSyncRunUpdate {
	_u.mutation.ClearUpstreamHash()
	return _u
}

// SetNormalizedHash sets the "normalized_hash" field.
func (_u *CatalogSyncRunUpdate) SetNormalizedHash(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetNormalizedHash(v)
	return _u
}

// SetNillableNormalizedHash sets the "normalized_hash" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableNormalizedHash(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetNormalizedHash(*v)
	}
	return _u
}

// ClearNormalizedHash clears the value of the "normalized_hash" field.
func (_u *CatalogSyncRunUpdate) ClearNormalizedHash() *CatalogSyncRunUpdate {
	_u.mutation.ClearNormalizedHash()
	return _u
}

// SetNormalizerVersion sets the "normalizer_version" field.
func (_u *CatalogSyncRunUpdate) SetNormalizerVersion(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetNormalizerVersion(v)
	return _u
}

// SetNillableNormalizerVersion sets the "normalizer_version" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableNormalizerVersion(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetNormalizerVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CatalogSyncRunUpdate) SetStatus(v string) *CatalogSyncRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableStatus(v *string) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceCount sets the "source_count" field.
func (_u *CatalogSyncRunUpdate) SetSourceCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.ResetSourceCount()
	_u.mutation.SetSourceCount(v)
	return _u
}

// SetNillableSourceCount sets the "source_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableSourceCount(v *int) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetSourceCount(*v)
	}
	return _u
}

// AddSourceCount adds value to the "source_count" field.
func (_u *CatalogSyncRunUpdate) AddSourceCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.AddSourceCount(v)
	return _u
}

// SetNormalizedCount sets the "normalized_count" field.
func (_u *CatalogSyncRunUpdate) SetNormalizedCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.ResetNormalizedCount()
	_u.mutation.SetNormalizedCount(v)
	return _u
}

// SetNillableNormalizedCount sets the "normalized_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableNormalizedCount(v *int) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetNormalizedCount(*v)
	}
	return _u
}

// AddNormalizedCount adds value to the "normalized_count" field.
func (_u *CatalogSyncRunUpdate) AddNormalizedCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.AddNormalizedCount(v)
	return _u
}

// SetAddedCount sets the "added_count" field.
func (_u *CatalogSyncRunUpdate) SetAddedCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.ResetAddedCount()
	_u.mutation.SetAddedCount(v)
	return _u
}

// SetNillableAddedCount sets the "added_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableAddedCount(v *int) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetAddedCount(*v)
	}
	return _u
}

// AddAddedCount adds value to the "added_count" field.
func (_u *CatalogSyncRunUpdate) AddAddedCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.AddAddedCount(v)
	return _u
}

// SetChangedCount sets the "changed_count" field.
func (_u *CatalogSyncRunUpdate) SetChangedCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.ResetChangedCount()
	_u.mutation.SetChangedCount(v)
	return _u
}

// SetNillableChangedCount sets the "changed_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableChangedCount(v *int) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetChangedCount(*v)
	}
	return _u
}

// AddChangedCount adds value to the "changed_count" field.
func (_u *CatalogSyncRunUpdate) AddChangedCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.AddChangedCount(v)
	return _u
}

// SetMissingCount sets the "missing_count" field.
func (_u *CatalogSyncRunUpdate) SetMissingCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.ResetMissingCount()
	_u.mutation.SetMissingCount(v)
	return _u
}

// SetNillableMissingCount sets the "missing_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableMissingCount(v *int) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetMissingCount(*v)
	}
	return _u
}

// AddMissingCount adds value to the "missing_count" field.
func (_u *CatalogSyncRunUpdate) AddMissingCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.AddMissingCount(v)
	return _u
}

// SetInvalidCount sets the "invalid_count" field.
func (_u *CatalogSyncRunUpdate) SetInvalidCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.ResetInvalidCount()
	_u.mutation.SetInvalidCount(v)
	return _u
}

// SetNillableInvalidCount sets the "invalid_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableInvalidCount(v *int) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetInvalidCount(*v)
	}
	return _u
}

// AddInvalidCount adds value to the "invalid_count" field.
func (_u *CatalogSyncRunUpdate) AddInvalidCount(v int) *CatalogSyncRunUpdate {
	_u.mutation.AddInvalidCount(v)
	return _u
}

// SetValidationErrors sets the "validation_errors" field.
func (_u *CatalogSyncRunUpdate) SetValidationErrors(v []interface{}) *CatalogSyncRunUpdate {
	_u.mutation.SetValidationErrors(v)
	return _u
}

// AppendValidationErrors appends value to the "validation_errors" field.
func (_u *CatalogSyncRunUpdate) AppendValidationErrors(v []interface{}) *CatalogSyncRunUpdate {
	_u.mutation.AppendValidationErrors(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CatalogSyncRunUpdate) SetStartedAt(v time.Time) *CatalogSyncRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableStartedAt(v *time.Time) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CatalogSyncRunUpdate) SetCompletedAt(v time.Time) *CatalogSyncRunUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CatalogSyncRunUpdate) SetNillableCompletedAt(v *time.Time) *CatalogSyncRunUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CatalogSyncRunUpdate) ClearCompletedAt() *CatalogSyncRunUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the CatalogSyncRunMutation object of the builder.
func (_u *CatalogSyncRunUpdate) Mutation() *CatalogSyncRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CatalogSyncRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogSyncRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CatalogSyncRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogSyncRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CatalogSyncRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(catalogsyncrun.Table, catalogsyncrun.Columns, sqlgraph.NewFieldSpec(catalogsyncrun.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceSet(); ok {
		_spec.SetField(catalogsyncrun.FieldSourceSet, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(catalogsyncrun.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(catalogsyncrun.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(catalogsyncrun.FieldActorUserID, field.TypeInt64, value)
	}
	if _u.mutation.ActorUserIDCleared() {
		_spec.ClearField(catalogsyncrun.FieldActorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamVersion(); ok {
		_spec.SetField(catalogsyncrun.FieldUpstreamVersion, field.TypeString, value)
	}
	if _u.mutation.UpstreamVersionCleared() {
		_spec.ClearField(catalogsyncrun.FieldUpstreamVersion, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamEtag(); ok {
		_spec.SetField(catalogsyncrun.FieldUpstreamEtag, field.TypeString, value)
	}
	if _u.mutation.UpstreamEtagCleared() {
		_spec.ClearField(catalogsyncrun.FieldUpstreamEtag, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamHash(); ok {
		_spec.SetField(catalogsyncrun.FieldUpstreamHash, field.TypeString, value)
	}
	if _u.mutation.UpstreamHashCleared() {
		_spec.ClearField(catalogsyncrun.FieldUpstreamHash, field.TypeString)
	}
	if value, ok := _u.mutation.NormalizedHash(); ok {
		_spec.SetField(catalogsyncrun.FieldNormalizedHash, field.TypeString, value)
	}
	if _u.mutation.NormalizedHashCleared() {
		_spec.ClearField(catalogsyncrun.FieldNormalizedHash, field.TypeString)
	}
	if value, ok := _u.mutation.NormalizerVersion(); ok {
		_spec.SetField(catalogsyncrun.FieldNormalizerVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(catalogsyncrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceCount(); ok {
		_spec.SetField(catalogsyncrun.FieldSourceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceCount(); ok {
		_spec.AddField(catalogsyncrun.FieldSourceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NormalizedCount(); ok {
		_spec.SetField(catalogsyncrun.FieldNormalizedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNormalizedCount(); ok {
		_spec.AddField(catalogsyncrun.FieldNormalizedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.SetField(catalogsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAddedCount(); ok {
		_spec.AddField(catalogsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChangedCount(); ok {
		_spec.SetField(catalogsyncrun.FieldChangedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChangedCount(); ok {
		_spec.AddField(catalogsyncrun.FieldChangedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MissingCount(); ok {
		_spec.SetField(catalogsyncrun.FieldMissingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMissingCount(); ok {
		_spec.AddField(catalogsyncrun.FieldMissingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InvalidCount(); ok {
		_spec.SetField(catalogsyncrun.FieldInvalidCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInvalidCount(); ok {
		_spec.AddField(catalogsyncrun.FieldInvalidCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidationErrors(); ok {
		_spec.SetField(catalogsyncrun.FieldValidationErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValidationErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, catalogsyncrun.FieldValidationErrors, value)
		})
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(catalogsyncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(catalogsyncrun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(catalogsyncrun.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogsyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CatalogSyncRunUpdateOne is the builder for updating a single CatalogSyncRun entity.
type CatalogSyncRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CatalogSyncRunMutation
}

// SetSourceSet sets the "source_set" field.
func (_u *CatalogSyncRunUpdateOne) SetSourceSet(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetSourceSet(v)
	return _u
}

// SetNillableSourceSet sets the "source_set" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableSourceSet(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetSourceSet(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *CatalogSyncRunUpdateOne) SetTrigger(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableTrigger(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *CatalogSyncRunUpdateOne) SetActorUserID(v int64) *CatalogSyncRunUpdateOne {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableActorUserID(v *int64) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *CatalogSyncRunUpdateOne) AddActorUserID(v int64) *CatalogSyncRunUpdateOne {
	_u.mutation.AddActorUserID(v)
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *CatalogSyncRunUpdateOne) ClearActorUserID() *CatalogSyncRunUpdateOne {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetUpstreamVersion sets the "upstream_version" field.
func (_u *CatalogSyncRunUpdateOne) SetUpstreamVersion(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetUpstreamVersion(v)
	return _u
}

// SetNillableUpstreamVersion sets the "upstream_version" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableUpstreamVersion(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetUpstreamVersion(*v)
	}
	return _u
}

// ClearUpstreamVersion clears the value of the "upstream_version" field.
func (_u *CatalogSyncRunUpdateOne) ClearUpstreamVersion() *CatalogSyncRunUpdateOne {
	_u.mutation.ClearUpstreamVersion()
	return _u
}

// SetUpstreamEtag sets the "upstream_etag" field.
func (_u *CatalogSyncRunUpdateOne) SetUpstreamEtag(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetUpstreamEtag(v)
	return _u
}

// SetNillableUpstreamEtag sets the "upstream_etag" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableUpstreamEtag(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetUpstreamEtag(*v)
	}
	return _u
}

// ClearUpstreamEtag clears the value of the "upstream_etag" field.
func (_u *CatalogSyncRunUpdateOne) ClearUpstreamEtag() *CatalogSyncRunUpdateOne {
	_u.mutation.ClearUpstreamEtag()
	return _u
}

// SetUpstreamHash sets the "upstream_hash" field.
func (_u *CatalogSyncRunUpdateOne) SetUpstreamHash(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetUpstreamHash(v)
	return _u
}

// SetNillableUpstreamHash sets the "upstream_hash" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableUpstreamHash(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetUpstreamHash(*v)
	}
	return _u
}

// ClearUpstreamHash clears the value of the "upstream_hash" field.
func (_u *CatalogSyncRunUpdateOne) ClearUpstreamHash() *CatalogSyncRunUpdateOne {
	_u.mutation.ClearUpstreamHash()
	return _u
}

// SetNormalizedHash sets the "normalized_hash" field.
func (_u *CatalogSyncRunUpdateOne) SetNormalizedHash(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetNormalizedHash(v)
	return _u
}

// SetNillableNormalizedHash sets the "normalized_hash" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableNormalizedHash(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetNormalizedHash(*v)
	}
	return _u
}

// ClearNormalizedHash clears the value of the "normalized_hash" field.
func (_u *CatalogSyncRunUpdateOne) ClearNormalizedHash() *CatalogSyncRunUpdateOne {
	_u.mutation.ClearNormalizedHash()
	return _u
}

// SetNormalizerVersion sets the "normalizer_version" field.
func (_u *CatalogSyncRunUpdateOne) SetNormalizerVersion(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetNormalizerVersion(v)
	return _u
}

// SetNillableNormalizerVersion sets the "normalizer_version" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableNormalizerVersion(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetNormalizerVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CatalogSyncRunUpdateOne) SetStatus(v string) *CatalogSyncRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableStatus(v *string) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceCount sets the "source_count" field.
func (_u *CatalogSyncRunUpdateOne) SetSourceCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.ResetSourceCount()
	_u.mutation.SetSourceCount(v)
	return _u
}

// SetNillableSourceCount sets the "source_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableSourceCount(v *int) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetSourceCount(*v)
	}
	return _u
}

// AddSourceCount adds value to the "source_count" field.
func (_u *CatalogSyncRunUpdateOne) AddSourceCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.AddSourceCount(v)
	return _u
}

// SetNormalizedCount sets the "normalized_count" field.
func (_u *CatalogSyncRunUpdateOne) SetNormalizedCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.ResetNormalizedCount()
	_u.mutation.SetNormalizedCount(v)
	return _u
}

// SetNillableNormalizedCount sets the "normalized_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableNormalizedCount(v *int) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetNormalizedCount(*v)
	}
	return _u
}

// AddNormalizedCount adds value to the "normalized_count" field.
func (_u *CatalogSyncRunUpdateOne) AddNormalizedCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.AddNormalizedCount(v)
	return _u
}

// SetAddedCount sets the "added_count" field.
func (_u *CatalogSyncRunUpdateOne) SetAddedCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.ResetAddedCount()
	_u.mutation.SetAddedCount(v)
	return _u
}

// SetNillableAddedCount sets the "added_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableAddedCount(v *int) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetAddedCount(*v)
	}
	return _u
}

// AddAddedCount adds value to the "added_count" field.
func (_u *CatalogSyncRunUpdateOne) AddAddedCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.AddAddedCount(v)
	return _u
}

// SetChangedCount sets the "changed_count" field.
func (_u *CatalogSyncRunUpdateOne) SetChangedCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.ResetChangedCount()
	_u.mutation.SetChangedCount(v)
	return _u
}

// SetNillableChangedCount sets the "changed_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableChangedCount(v *int) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetChangedCount(*v)
	}
	return _u
}

// AddChangedCount adds value to the "changed_count" field.
func (_u *CatalogSyncRunUpdateOne) AddChangedCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.AddChangedCount(v)
	return _u
}

// SetMissingCount sets the "missing_count" field.
func (_u *CatalogSyncRunUpdateOne) SetMissingCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.ResetMissingCount()
	_u.mutation.SetMissingCount(v)
	return _u
}

// SetNillableMissingCount sets the "missing_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableMissingCount(v *int) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetMissingCount(*v)
	}
	return _u
}

// AddMissingCount adds value to the "missing_count" field.
func (_u *CatalogSyncRunUpdateOne) AddMissingCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.AddMissingCount(v)
	return _u
}

// SetInvalidCount sets the "invalid_count" field.
func (_u *CatalogSyncRunUpdateOne) SetInvalidCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.ResetInvalidCount()
	_u.mutation.SetInvalidCount(v)
	return _u
}

// SetNillableInvalidCount sets the "invalid_count" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableInvalidCount(v *int) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetInvalidCount(*v)
	}
	return _u
}

// AddInvalidCount adds value to the "invalid_count" field.
func (_u *CatalogSyncRunUpdateOne) AddInvalidCount(v int) *CatalogSyncRunUpdateOne {
	_u.mutation.AddInvalidCount(v)
	return _u
}

// SetValidationErrors sets the "validation_errors" field.
func (_u *CatalogSyncRunUpdateOne) SetValidationErrors(v []interface{}) *CatalogSyncRunUpdateOne {
	_u.mutation.SetValidationErrors(v)
	return _u
}

// AppendValidationErrors appends value to the "validation_errors" field.
func (_u *CatalogSyncRunUpdateOne) AppendValidationErrors(v []interface{}) *CatalogSyncRunUpdateOne {
	_u.mutation.AppendValidationErrors(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CatalogSyncRunUpdateOne) SetStartedAt(v time.Time) *CatalogSyncRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableStartedAt(v *time.Time) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CatalogSyncRunUpdateOne) SetCompletedAt(v time.Time) *CatalogSyncRunUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CatalogSyncRunUpdateOne) SetNillableCompletedAt(v *time.Time) *CatalogSyncRunUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CatalogSyncRunUpdateOne) ClearCompletedAt() *CatalogSyncRunUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the CatalogSyncRunMutation object of the builder.
func (_u *CatalogSyncRunUpdateOne) Mutation() *CatalogSyncRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the CatalogSyncRunUpdate builder.
func (_u *CatalogSyncRunUpdateOne) Where(ps ...predicate.CatalogSyncRun) *CatalogSyncRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CatalogSyncRunUpdateOne) Select(field string, fields ...string) *CatalogSyncRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CatalogSyncRun entity.
func (_u *CatalogSyncRunUpdateOne) Save(ctx context.Context) (*CatalogSyncRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogSyncRunUpdateOne) SaveX(ctx context.Context) *CatalogSyncRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CatalogSyncRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogSyncRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CatalogSyncRunUpdateOne) sqlSave(ctx context.Context) (_node *CatalogSyncRun, err error) {
	_spec := sqlgraph.NewUpdateSpec(catalogsyncrun.Table, catalogsyncrun.Columns, sqlgraph.NewFieldSpec(catalogsyncrun.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CatalogSyncRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, catalogsyncrun.FieldID)
		for _, f := range fields {
			if !catalogsyncrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != catalogsyncrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceSet(); ok {
		_spec.SetField(catalogsyncrun.FieldSourceSet, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(catalogsyncrun.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(catalogsyncrun.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(catalogsyncrun.FieldActorUserID, field.TypeInt64, value)
	}
	if _u.mutation.ActorUserIDCleared() {
		_spec.ClearField(catalogsyncrun.FieldActorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamVersion(); ok {
		_spec.SetField(catalogsyncrun.FieldUpstreamVersion, field.TypeString, value)
	}
	if _u.mutation.UpstreamVersionCleared() {
		_spec.ClearField(catalogsyncrun.FieldUpstreamVersion, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamEtag(); ok {
		_spec.SetField(catalogsyncrun.FieldUpstreamEtag, field.TypeString, value)
	}
	if _u.mutation.UpstreamEtagCleared() {
		_spec.ClearField(catalogsyncrun.FieldUpstreamEtag, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamHash(); ok {
		_spec.SetField(catalogsyncrun.FieldUpstreamHash, field.TypeString, value)
	}
	if _u.mutation.UpstreamHashCleared() {
		_spec.ClearField(catalogsyncrun.FieldUpstreamHash, field.TypeString)
	}
	if value, ok := _u.mutation.NormalizedHash(); ok {
		_spec.SetField(catalogsyncrun.FieldNormalizedHash, field.TypeString, value)
	}
	if _u.mutation.NormalizedHashCleared() {
		_spec.ClearField(catalogsyncrun.FieldNormalizedHash, field.TypeString)
	}
	if value, ok := _u.mutation.NormalizerVersion(); ok {
		_spec.SetField(catalogsyncrun.FieldNormalizerVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(catalogsyncrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceCount(); ok {
		_spec.SetField(catalogsyncrun.FieldSourceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceCount(); ok {
		_spec.AddField(catalogsyncrun.FieldSourceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NormalizedCount(); ok {
		_spec.SetField(catalogsyncrun.FieldNormalizedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNormalizedCount(); ok {
		_spec.AddField(catalogsyncrun.FieldNormalizedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.SetField(catalogsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAddedCount(); ok {
		_spec.AddField(catalogsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChangedCount(); ok {
		_spec.SetField(catalogsyncrun.FieldChangedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChangedCount(); ok {
		_spec.AddField(catalogsyncrun.FieldChangedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MissingCount(); ok {
		_spec.SetField(catalogsyncrun.FieldMissingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMissingCount(); ok {
		_spec.AddField(catalogsyncrun.FieldMissingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InvalidCount(); ok {
		_spec.SetField(catalogsyncrun.FieldInvalidCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInvalidCount(); ok {
		_spec.AddField(catalogsyncrun.FieldInvalidCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidationErrors(); ok {
		_spec.SetField(catalogsyncrun.FieldValidationErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValidationErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, catalogsyncrun.FieldValidationErrors, value)
		})
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(catalogsyncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(catalogsyncrun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(catalogsyncrun.FieldCompletedAt, field.TypeTime)
	}
	_node = &CatalogSyncRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogsyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
