// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catalogoutbox"
)

// CatalogOutboxCreate is the builder for creating a CatalogOutbox entity.
type CatalogOutboxCreate struct {
	config
	mutation *CatalogOutboxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEventType sets the "event_type" field.
func (_c *CatalogOutboxCreate) SetEventType(v string) *CatalogOutboxCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *CatalogOutboxCreate) SetScope(v string) *CatalogOutboxCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetPublicationEpoch sets the "publication_epoch" field.
func (_c *CatalogOutboxCreate) SetPublicationEpoch(v int64) *CatalogOutboxCreate {
	_c.mutation.SetPublicationEpoch(v)
	return _c
}

// SetCatalogRevisionID sets the "catalog_revision_id" field.
func (_c *CatalogOutboxCreate) SetCatalogRevisionID(v int64) *CatalogOutboxCreate {
	_c.mutation.SetCatalogRevisionID(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *CatalogOutboxCreate) SetModelID(v int64) *CatalogOutboxCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_c *CatalogOutboxCreate) SetNillableModelID(v *int64) *CatalogOutboxCreate {
	if v != nil {
		_c.SetModelID(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *CatalogOutboxCreate) SetPayload(v map[string]interface{}) *CatalogOutboxCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetDedupKey sets the "dedup_key" field.
func (_c *CatalogOutboxCreate) SetDedupKey(v string) *CatalogOutboxCreate {
	_c.mutation.SetDedupKey(v)
	return _c
}

// SetNillableDedupKey sets the "dedup_key" field if the given value is not nil.
func (_c *CatalogOutboxCreate) SetNillableDedupKey(v *string) *CatalogOutboxCreate {
	if v != nil {
		_c.SetDedupKey(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CatalogOutboxCreate) SetCreatedAt(v time.Time) *CatalogOutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CatalogOutboxCreate) SetNillableCreatedAt(v *time.Time) *CatalogOutboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CatalogOutboxMutation object of the builder.
func (_c *CatalogOutboxCreate) Mutation() *CatalogOutboxMutation {
	return _c.mutation
}

// Save creates the CatalogOutbox in the database.
func (_c *CatalogOutboxCreate) Save(ctx context.Context) (*CatalogOutbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CatalogOutboxCreate) SaveX(ctx context.Context) *CatalogOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CatalogOutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CatalogOutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CatalogOutboxCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := catalogoutbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CatalogOutboxCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "CatalogOutbox.event_type"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "CatalogOutbox.scope"`)}
	}
	if _, ok := _c.mutation.PublicationEpoch(); !ok {
		return &ValidationError{Name: "publication_epoch", err: errors.New(`ent: missing required field "CatalogOutbox.publication_epoch"`)}
	}
	if _, ok := _c.mutation.CatalogRevisionID(); !ok {
		return &ValidationError{Name: "catalog_revision_id", err: errors.New(`ent: missing required field "CatalogOutbox.catalog_revision_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CatalogOutbox.created_at"`)}
	}
	return nil
}

func (_c *CatalogOutboxCreate) sqlSave(ctx context.Context) (*CatalogOutbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CatalogOutboxCreate) createSpec() (*CatalogOutbox, *sqlgraph.CreateSpec) {
	var (
		_node = &CatalogOutbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(catalogoutbox.Table, sqlgraph.NewFieldSpec(catalogoutbox.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(catalogoutbox.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(catalogoutbox.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.PublicationEpoch(); ok {
		_spec.SetField(catalogoutbox.FieldPublicationEpoch, field.TypeInt64, value)
		_node.PublicationEpoch = value
	}
	if value, ok := _c.mutation.CatalogRevisionID(); ok {
		_spec.SetField(catalogoutbox.FieldCatalogRevisionID, field.TypeInt64, value)
		_node.CatalogRevisionID = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(catalogoutbox.FieldModelID, field.TypeInt64, value)
		_node.ModelID = &value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(catalogoutbox.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.DedupKey(); ok {
		_spec.SetField(catalogoutbox.FieldDedupKey, field.TypeString, value)
		_node.DedupKey = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(catalogoutbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CatalogOutbox.Create().
//		SetEventType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CatalogOutboxUpsert) {
//			SetEventType(v+v).
//		}).
//		Exec(ctx)
func (_c *CatalogOutboxCreate) OnConflict(opts ...sql.ConflictOption) *CatalogOutboxUpsertOne {
	_c.conflict = opts
	return &CatalogOutboxUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CatalogOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CatalogOutboxCreate) OnConflictColumns(columns ...string) *CatalogOutboxUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CatalogOutboxUpsertOne{
		create: _c,
	}
}

type (
	// CatalogOutboxUpsertOne is the builder for "upsert"-ing
	//  one CatalogOutbox node.
	CatalogOutboxUpsertOne struct {
		create *CatalogOutboxCreate
	}

	// CatalogOutboxUpsert is the "OnConflict" setter.
	CatalogOutboxUpsert struct {
		*sql.UpdateSet
	}
)

// SetEventType sets the "event_type" field.
func (u *CatalogOutboxUpsert) SetEventType(v string) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdateEventType() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldEventType)
	return u
}

// SetScope sets the "scope" field.
func (u *CatalogOutboxUpsert) SetScope(v string) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdateScope() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldScope)
	return u
}

// SetPublicationEpoch sets the "publication_epoch" field.
func (u *CatalogOutboxUpsert) SetPublicationEpoch(v int64) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldPublicationEpoch, v)
	return u
}

// UpdatePublicationEpoch sets the "publication_epoch" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdatePublicationEpoch() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldPublicationEpoch)
	return u
}

// AddPublicationEpoch adds v to the "publication_epoch" field.
func (u *CatalogOutboxUpsert) AddPublicationEpoch(v int64) *CatalogOutboxUpsert {
	u.Add(catalogoutbox.FieldPublicationEpoch, v)
	return u
}

// SetCatalogRevisionID sets the "catalog_revision_id" field.
func (u *CatalogOutboxUpsert) SetCatalogRevisionID(v int64) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldCatalogRevisionID, v)
	return u
}

// UpdateCatalogRevisionID sets the "catalog_revision_id" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdateCatalogRevisionID() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldCatalogRevisionID)
	return u
}

// AddCatalogRevisionID adds v to the "catalog_revision_id" field.
func (u *CatalogOutboxUpsert) AddCatalogRevisionID(v int64) *CatalogOutboxUpsert {
	u.Add(catalogoutbox.FieldCatalogRevisionID, v)
	return u
}

// SetModelID sets the "model_id" field.
func (u *CatalogOutboxUpsert) SetModelID(v int64) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdateModelID() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldModelID)
	return u
}

// AddModelID adds v to the "model_id" field.
func (u *CatalogOutboxUpsert) AddModelID(v int64) *CatalogOutboxUpsert {
	u.Add(catalogoutbox.FieldModelID, v)
	return u
}

// ClearModelID clears the value of the "model_id" field.
func (u *CatalogOutboxUpsert) ClearModelID() *CatalogOutboxUpsert {
	u.SetNull(catalogoutbox.FieldModelID)
	return u
}

// SetPayload sets the "payload" field.
func (u *CatalogOutboxUpsert) SetPayload(v map[string]interface{}) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdatePayload() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *CatalogOutboxUpsert) ClearPayload() *CatalogOutboxUpsert {
	u.SetNull(catalogoutbox.FieldPayload)
	return u
}

// SetDedupKey sets the "dedup_key" field.
func (u *CatalogOutboxUpsert) SetDedupKey(v string) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldDedupKey, v)
	return u
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdateDedupKey() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldDedupKey)
	return u
}

// ClearDedupKey clears the value of the "dedup_key" field.
func (u *CatalogOutboxUpsert) ClearDedupKey() *CatalogOutboxUpsert {
	u.SetNull(catalogoutbox.FieldDedupKey)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CatalogOutboxUpsert) SetCreatedAt(v time.Time) *CatalogOutboxUpsert {
	u.Set(catalogoutbox.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CatalogOutboxUpsert) UpdateCreatedAt() *CatalogOutboxUpsert {
	u.SetExcluded(catalogoutbox.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CatalogOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CatalogOutboxUpsertOne) UpdateNewValues() *CatalogOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CatalogOutbox.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CatalogOutboxUpsertOne) Ignore() *CatalogOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CatalogOutboxUpsertOne) DoNothing() *CatalogOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CatalogOutboxCreate.OnConflict
// documentation for more info.
func (u *CatalogOutboxUpsertOne) Update(set func(*CatalogOutboxUpsert)) *CatalogOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CatalogOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventType sets the "event_type" field.
func (u *CatalogOutboxUpsertOne) SetEventType(v string) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdateEventType() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateEventType()
	})
}

// SetScope sets the "scope" field.
func (u *CatalogOutboxUpsertOne) SetScope(v string) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdateScope() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateScope()
	})
}

// SetPublicationEpoch sets the "publication_epoch" field.
func (u *CatalogOutboxUpsertOne) SetPublicationEpoch(v int64) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetPublicationEpoch(v)
	})
}

// AddPublicationEpoch adds v to the "publication_epoch" field.
func (u *CatalogOutboxUpsertOne) AddPublicationEpoch(v int64) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.AddPublicationEpoch(v)
	})
}

// UpdatePublicationEpoch sets the "publication_epoch" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdatePublicationEpoch() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdatePublicationEpoch()
	})
}

// SetCatalogRevisionID sets the "catalog_revision_id" field.
func (u *CatalogOutboxUpsertOne) SetCatalogRevisionID(v int64) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetCatalogRevisionID(v)
	})
}

// AddCatalogRevisionID adds v to the "catalog_revision_id" field.
func (u *CatalogOutboxUpsertOne) AddCatalogRevisionID(v int64) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.AddCatalogRevisionID(v)
	})
}

// UpdateCatalogRevisionID sets the "catalog_revision_id" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdateCatalogRevisionID() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateCatalogRevisionID()
	})
}

// SetModelID sets the "model_id" field.
func (u *CatalogOutboxUpsertOne) SetModelID(v int64) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetModelID(v)
	})
}

// AddModelID adds v to the "model_id" field.
func (u *CatalogOutboxUpsertOne) AddModelID(v int64) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.AddModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdateModelID() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateModelID()
	})
}

// ClearModelID clears the value of the "model_id" field.
func (u *CatalogOutboxUpsertOne) ClearModelID() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.ClearModelID()
	})
}

// SetPayload sets the "payload" field.
func (u *CatalogOutboxUpsertOne) SetPayload(v map[string]interface{}) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdatePayload() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *CatalogOutboxUpsertOne) ClearPayload() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.ClearPayload()
	})
}

// SetDedupKey sets the "dedup_key" field.
func (u *CatalogOutboxUpsertOne) SetDedupKey(v string) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetDedupKey(v)
	})
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdateDedupKey() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateDedupKey()
	})
}

// ClearDedupKey clears the value of the "dedup_key" field.
func (u *CatalogOutboxUpsertOne) ClearDedupKey() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.ClearDedupKey()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CatalogOutboxUpsertOne) SetCreatedAt(v time.Time) *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CatalogOutboxUpsertOne) UpdateCreatedAt() *CatalogOutboxUpsertOne {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CatalogOutboxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CatalogOutboxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CatalogOutboxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CatalogOutboxUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CatalogOutboxUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CatalogOutboxCreateBulk is the builder for creating many CatalogOutbox entities in bulk.
type CatalogOutboxCreateBulk struct {
	config
	err      error
	builders []*CatalogOutboxCreate
	conflict []sql.ConflictOption
}

// Save creates the CatalogOutbox entities in the database.
func (_c *CatalogOutboxCreateBulk) Save(ctx context.Context) ([]*CatalogOutbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CatalogOutbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CatalogOutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CatalogOutboxCreateBulk) SaveX(ctx context.Context) []*CatalogOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CatalogOutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CatalogOutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CatalogOutbox.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CatalogOutboxUpsert) {
//			SetEventType(v+v).
//		}).
//		Exec(ctx)
func (_c *CatalogOutboxCreateBulk) OnConflict(opts ...sql.ConflictOption) *CatalogOutboxUpsertBulk {
	_c.conflict = opts
	return &CatalogOutboxUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CatalogOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CatalogOutboxCreateBulk) OnConflictColumns(columns ...string) *CatalogOutboxUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CatalogOutboxUpsertBulk{
		create: _c,
	}
}

// CatalogOutboxUpsertBulk is the builder for "upsert"-ing
// a bulk of CatalogOutbox nodes.
type CatalogOutboxUpsertBulk struct {
	create *CatalogOutboxCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CatalogOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CatalogOutboxUpsertBulk) UpdateNewValues() *CatalogOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CatalogOutbox.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CatalogOutboxUpsertBulk) Ignore() *CatalogOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CatalogOutboxUpsertBulk) DoNothing() *CatalogOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CatalogOutboxCreateBulk.OnConflict
// documentation for more info.
func (u *CatalogOutboxUpsertBulk) Update(set func(*CatalogOutboxUpsert)) *CatalogOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CatalogOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventType sets the "event_type" field.
func (u *CatalogOutboxUpsertBulk) SetEventType(v string) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdateEventType() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateEventType()
	})
}

// SetScope sets the "scope" field.
func (u *CatalogOutboxUpsertBulk) SetScope(v string) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdateScope() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateScope()
	})
}

// SetPublicationEpoch sets the "publication_epoch" field.
func (u *CatalogOutboxUpsertBulk) SetPublicationEpoch(v int64) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetPublicationEpoch(v)
	})
}

// AddPublicationEpoch adds v to the "publication_epoch" field.
func (u *CatalogOutboxUpsertBulk) AddPublicationEpoch(v int64) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.AddPublicationEpoch(v)
	})
}

// UpdatePublicationEpoch sets the "publication_epoch" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdatePublicationEpoch() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdatePublicationEpoch()
	})
}

// SetCatalogRevisionID sets the "catalog_revision_id" field.
func (u *CatalogOutboxUpsertBulk) SetCatalogRevisionID(v int64) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetCatalogRevisionID(v)
	})
}

// AddCatalogRevisionID adds v to the "catalog_revision_id" field.
func (u *CatalogOutboxUpsertBulk) AddCatalogRevisionID(v int64) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.AddCatalogRevisionID(v)
	})
}

// UpdateCatalogRevisionID sets the "catalog_revision_id" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdateCatalogRevisionID() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateCatalogRevisionID()
	})
}

// SetModelID sets the "model_id" field.
func (u *CatalogOutboxUpsertBulk) SetModelID(v int64) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetModelID(v)
	})
}

// AddModelID adds v to the "model_id" field.
func (u *CatalogOutboxUpsertBulk) AddModelID(v int64) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.AddModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdateModelID() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateModelID()
	})
}

// ClearModelID clears the value of the "model_id" field.
func (u *CatalogOutboxUpsertBulk) ClearModelID() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.ClearModelID()
	})
}

// SetPayload sets the "payload" field.
func (u *CatalogOutboxUpsertBulk) SetPayload(v map[string]interface{}) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdatePayload() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *CatalogOutboxUpsertBulk) ClearPayload() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.ClearPayload()
	})
}

// SetDedupKey sets the "dedup_key" field.
func (u *CatalogOutboxUpsertBulk) SetDedupKey(v string) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetDedupKey(v)
	})
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdateDedupKey() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateDedupKey()
	})
}

// ClearDedupKey clears the value of the "dedup_key" field.
func (u *CatalogOutboxUpsertBulk) ClearDedupKey() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.ClearDedupKey()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CatalogOutboxUpsertBulk) SetCreatedAt(v time.Time) *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CatalogOutboxUpsertBulk) UpdateCreatedAt() *CatalogOutboxUpsertBulk {
	return u.Update(func(s *CatalogOutboxUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CatalogOutboxUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CatalogOutboxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CatalogOutboxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CatalogOutboxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
