// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catalogmodelrevision"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CatalogModelRevisionUpdate is the builder for updating CatalogModelRevision entities.
type CatalogModelRevisionUpdate struct {
	config
	hooks    []Hook
	mutation *CatalogModelRevisionMutation
}

// Where appends a list predicates to the CatalogModelRevisionUpdate builder.
func (_u *CatalogModelRevisionUpdate) Where(ps ...predicate.CatalogModelRevision) *CatalogModelRevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCatalogRevisionID sets the "catalog_revision_id" field.
func (_u *CatalogModelRevisionUpdate) SetCatalogRevisionID(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.ResetCatalogRevisionID()
	_u.mutation.SetCatalogRevisionID(v)
	return _u
}

// SetNillableCatalogRevisionID sets the "catalog_revision_id" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableCatalogRevisionID(v *int64) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetCatalogRevisionID(*v)
	}
	return _u
}

// AddCatalogRevisionID adds value to the "catalog_revision_id" field.
func (_u *CatalogModelRevisionUpdate) AddCatalogRevisionID(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.AddCatalogRevisionID(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *CatalogModelRevisionUpdate) SetModelID(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableModelID(v *int64) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *CatalogModelRevisionUpdate) AddModelID(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.AddModelID(v)
	return _u
}

// SetSourceState sets the "source_state" field.
func (_u *CatalogModelRevisionUpdate) SetSourceState(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetSourceState(v)
	return _u
}

// SetNillableSourceState sets the "source_state" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableSourceState(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetSourceState(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CatalogModelRevisionUpdate) SetProvider(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableProvider(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CatalogModelRevisionUpdate) SetPlatform(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillablePlatform(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *CatalogModelRevisionUpdate) SetMode(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableMode(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *CatalogModelRevisionUpdate) SetCapabilities(v map[string]interface{}) *CatalogModelRevisionUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *CatalogModelRevisionUpdate) SetContextWindow(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableContextWindow(v *int64) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *CatalogModelRevisionUpdate) AddContextWindow(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *CatalogModelRevisionUpdate) ClearContextWindow() *CatalogModelRevisionUpdate {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *CatalogModelRevisionUpdate) SetMaxOutputTokens(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableMaxOutputTokens(v *int64) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *CatalogModelRevisionUpdate) AddMaxOutputTokens(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (_u *CatalogModelRevisionUpdate) ClearMaxOutputTokens() *CatalogModelRevisionUpdate {
	_u.mutation.ClearMaxOutputTokens()
	return _u
}

// SetPricingSchemaVersion sets the "pricing_schema_version" field.
func (_u *CatalogModelRevisionUpdate) SetPricingSchemaVersion(v int) *CatalogModelRevisionUpdate {
	_u.mutation.ResetPricingSchemaVersion()
	_u.mutation.SetPricingSchemaVersion(v)
	return _u
}

// SetNillablePricingSchemaVersion sets the "pricing_schema_version" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillablePricingSchemaVersion(v *int) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetPricingSchemaVersion(*v)
	}
	return _u
}

// AddPricingSchemaVersion adds value to the "pricing_schema_version" field.
func (_u *CatalogModelRevisionUpdate) AddPricingSchemaVersion(v int) *CatalogModelRevisionUpdate {
	_u.mutation.AddPricingSchemaVersion(v)
	return _u
}

// SetPricingJSON sets the "pricing_json" field.
func (_u *CatalogModelRevisionUpdate) SetPricingJSON(v map[string]interface{}) *CatalogModelRevisionUpdate {
	_u.mutation.SetPricingJSON(v)
	return _u
}

// ClearPricingJSON clears the value of the "pricing_json" field.
func (_u *CatalogModelRevisionUpdate) ClearPricingJSON() *CatalogModelRevisionUpdate {
	_u.mutation.ClearPricingJSON()
	return _u
}

// SetPricingValid sets the "pricing_valid" field.
func (_u *CatalogModelRevisionUpdate) SetPricingValid(v bool) *CatalogModelRevisionUpdate {
	_u.mutation.SetPricingValid(v)
	return _u
}

// SetNillablePricingValid sets the "pricing_valid" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillablePricingValid(v *bool) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetPricingValid(*v)
	}
	return _u
}

// SetOperatorState sets the "operator_state" field.
func (_u *CatalogModelRevisionUpdate) SetOperatorState(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetOperatorState(v)
	return _u
}

// SetNillableOperatorState sets the "operator_state" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableOperatorState(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetOperatorState(*v)
	}
	return _u
}

// SetOperatorReason sets the "operator_reason" field.
func (_u *CatalogModelRevisionUpdate) SetOperatorReason(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetOperatorReason(v)
	return _u
}

// SetNillableOperatorReason sets the "operator_reason" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableOperatorReason(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetOperatorReason(*v)
	}
	return _u
}

// ClearOperatorReason clears the value of the "operator_reason" field.
func (_u *CatalogModelRevisionUpdate) ClearOperatorReason() *CatalogModelRevisionUpdate {
	_u.mutation.ClearOperatorReason()
	return _u
}

// SetOperatorVersion sets the "operator_version" field.
func (_u *CatalogModelRevisionUpdate) SetOperatorVersion(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.ResetOperatorVersion()
	_u.mutation.SetOperatorVersion(v)
	return _u
}

// SetNillableOperatorVersion sets the "operator_version" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableOperatorVersion(v *int64) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetOperatorVersion(*v)
	}
	return _u
}

// AddOperatorVersion adds value to the "operator_version" field.
func (_u *CatalogModelRevisionUpdate) AddOperatorVersion(v int64) *CatalogModelRevisionUpdate {
	_u.mutation.AddOperatorVersion(v)
	return _u
}

// SetPricingSource sets the "pricing_source" field.
func (_u *CatalogModelRevisionUpdate) SetPricingSource(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetPricingSource(v)
	return _u
}

// SetNillablePricingSource sets the "pricing_source" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillablePricingSource(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetPricingSource(*v)
	}
	return _u
}

// ClearPricingSource clears the value of the "pricing_source" field.
func (_u *CatalogModelRevisionUpdate) ClearPricingSource() *CatalogModelRevisionUpdate {
	_u.mutation.ClearPricingSource()
	return _u
}

// SetSourceMetadata sets the "source_metadata" field.
func (_u *CatalogModelRevisionUpdate) SetSourceMetadata(v map[string]interface{}) *CatalogModelRevisionUpdate {
	_u.mutation.SetSourceMetadata(v)
	return _u
}

// SetSourceHash sets the "source_hash" field.
func (_u *CatalogModelRevisionUpdate) SetSourceHash(v string) *CatalogModelRevisionUpdate {
	_u.mutation.SetSourceHash(v)
	return _u
}

// SetNillableSourceHash sets the "source_hash" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableSourceHash(v *string) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetSourceHash(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CatalogModelRevisionUpdate) SetCreatedAt(v time.Time) *CatalogModelRevisionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdate) SetNillableCreatedAt(v *time.Time) *CatalogModelRevisionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CatalogModelRevisionMutation object of the builder.
func (_u *CatalogModelRevisionUpdate) Mutation() *CatalogModelRevisionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CatalogModelRevisionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogModelRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CatalogModelRevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogModelRevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CatalogModelRevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(catalogmodelrevision.Table, catalogmodelrevision.Columns, sqlgraph.NewFieldSpec(catalogmodelrevision.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CatalogRevisionID(); ok {
		_spec.SetField(catalogmodelrevision.FieldCatalogRevisionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCatalogRevisionID(); ok {
		_spec.AddField(catalogmodelrevision.FieldCatalogRevisionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(catalogmodelrevision.FieldModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(catalogmodelrevision.FieldModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceState(); ok {
		_spec.SetField(catalogmodelrevision.FieldSourceState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(catalogmodelrevision.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(catalogmodelrevision.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(catalogmodelrevision.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(catalogmodelrevision.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(catalogmodelrevision.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(catalogmodelrevision.FieldContextWindow, field.TypeInt64, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(catalogmodelrevision.FieldContextWindow, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(catalogmodelrevision.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(catalogmodelrevision.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if _u.mutation.MaxOutputTokensCleared() {
		_spec.ClearField(catalogmodelrevision.FieldMaxOutputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.PricingSchemaVersion(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricingSchemaVersion(); ok {
		_spec.AddField(catalogmodelrevision.FieldPricingSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PricingJSON(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingJSON, field.TypeJSON, value)
	}
	if _u.mutation.PricingJSONCleared() {
		_spec.ClearField(catalogmodelrevision.FieldPricingJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.PricingValid(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingValid, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OperatorState(); ok {
		_spec.SetField(catalogmodelrevision.FieldOperatorState, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorReason(); ok {
		_spec.SetField(catalogmodelrevision.FieldOperatorReason, field.TypeString, value)
	}
	if _u.mutation.OperatorReasonCleared() {
		_spec.ClearField(catalogmodelrevision.FieldOperatorReason, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorVersion(); ok {
		_spec.SetField(catalogmodelrevision.FieldOperatorVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorVersion(); ok {
		_spec.AddField(catalogmodelrevision.FieldOperatorVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PricingSource(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingSource, field.TypeString, value)
	}
	if _u.mutation.PricingSourceCleared() {
		_spec.ClearField(catalogmodelrevision.FieldPricingSource, field.TypeString)
	}
	if value, ok := _u.mutation.SourceMetadata(); ok {
		_spec.SetField(catalogmodelrevision.FieldSourceMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SourceHash(); ok {
		_spec.SetField(catalogmodelrevision.FieldSourceHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(catalogmodelrevision.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogmodelrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CatalogModelRevisionUpdateOne is the builder for updating a single CatalogModelRevision entity.
type CatalogModelRevisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CatalogModelRevisionMutation
}

// SetCatalogRevisionID sets the "catalog_revision_id" field.
func (_u *CatalogModelRevisionUpdateOne) SetCatalogRevisionID(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.ResetCatalogRevisionID()
	_u.mutation.SetCatalogRevisionID(v)
	return _u
}

// SetNillableCatalogRevisionID sets the "catalog_revision_id" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableCatalogRevisionID(v *int64) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetCatalogRevisionID(*v)
	}
	return _u
}

// AddCatalogRevisionID adds value to the "catalog_revision_id" field.
func (_u *CatalogModelRevisionUpdateOne) AddCatalogRevisionID(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.AddCatalogRevisionID(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *CatalogModelRevisionUpdateOne) SetModelID(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableModelID(v *int64) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *CatalogModelRevisionUpdateOne) AddModelID(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.AddModelID(v)
	return _u
}

// SetSourceState sets the "source_state" field.
func (_u *CatalogModelRevisionUpdateOne) SetSourceState(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetSourceState(v)
	return _u
}

// SetNillableSourceState sets the "source_state" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableSourceState(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetSourceState(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CatalogModelRevisionUpdateOne) SetProvider(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableProvider(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CatalogModelRevisionUpdateOne) SetPlatform(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillablePlatform(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *CatalogModelRevisionUpdateOne) SetMode(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableMode(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *CatalogModelRevisionUpdateOne) SetCapabilities(v map[string]interface{}) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *CatalogModelRevisionUpdateOne) SetContextWindow(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableContextWindow(v *int64) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *CatalogModelRevisionUpdateOne) AddContextWindow(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *CatalogModelRevisionUpdateOne) ClearContextWindow() *CatalogModelRevisionUpdateOne {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *CatalogModelRevisionUpdateOne) SetMaxOutputTokens(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableMaxOutputTokens(v *int64) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *CatalogModelRevisionUpdateOne) AddMaxOutputTokens(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (_u *CatalogModelRevisionUpdateOne) ClearMaxOutputTokens() *CatalogModelRevisionUpdateOne {
	_u.mutation.ClearMaxOutputTokens()
	return _u
}

// SetPricingSchemaVersion sets the "pricing_schema_version" field.
func (_u *CatalogModelRevisionUpdateOne) SetPricingSchemaVersion(v int) *CatalogModelRevisionUpdateOne {
	_u.mutation.ResetPricingSchemaVersion()
	_u.mutation.SetPricingSchemaVersion(v)
	return _u
}

// SetNillablePricingSchemaVersion sets the "pricing_schema_version" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillablePricingSchemaVersion(v *int) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetPricingSchemaVersion(*v)
	}
	return _u
}

// AddPricingSchemaVersion adds value to the "pricing_schema_version" field.
func (_u *CatalogModelRevisionUpdateOne) AddPricingSchemaVersion(v int) *CatalogModelRevisionUpdateOne {
	_u.mutation.AddPricingSchemaVersion(v)
	return _u
}

// SetPricingJSON sets the "pricing_json" field.
func (_u *CatalogModelRevisionUpdateOne) SetPricingJSON(v map[string]interface{}) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetPricingJSON(v)
	return _u
}

// ClearPricingJSON clears the value of the "pricing_json" field.
func (_u *CatalogModelRevisionUpdateOne) ClearPricingJSON() *CatalogModelRevisionUpdateOne {
	_u.mutation.ClearPricingJSON()
	return _u
}

// SetPricingValid sets the "pricing_valid" field.
func (_u *CatalogModelRevisionUpdateOne) SetPricingValid(v bool) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetPricingValid(v)
	return _u
}

// SetNillablePricingValid sets the "pricing_valid" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillablePricingValid(v *bool) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetPricingValid(*v)
	}
	return _u
}

// SetOperatorState sets the "operator_state" field.
func (_u *CatalogModelRevisionUpdateOne) SetOperatorState(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetOperatorState(v)
	return _u
}

// SetNillableOperatorState sets the "operator_state" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableOperatorState(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetOperatorState(*v)
	}
	return _u
}

// SetOperatorReason sets the "operator_reason" field.
func (_u *CatalogModelRevisionUpdateOne) SetOperatorReason(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetOperatorReason(v)
	return _u
}

// SetNillableOperatorReason sets the "operator_reason" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableOperatorReason(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetOperatorReason(*v)
	}
	return _u
}

// ClearOperatorReason clears the value of the "operator_reason" field.
func (_u *CatalogModelRevisionUpdateOne) ClearOperatorReason() *CatalogModelRevisionUpdateOne {
	_u.mutation.ClearOperatorReason()
	return _u
}

// SetOperatorVersion sets the "operator_version" field.
func (_u *CatalogModelRevisionUpdateOne) SetOperatorVersion(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.ResetOperatorVersion()
	_u.mutation.SetOperatorVersion(v)
	return _u
}

// SetNillableOperatorVersion sets the "operator_version" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableOperatorVersion(v *int64) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetOperatorVersion(*v)
	}
	return _u
}

// AddOperatorVersion adds value to the "operator_version" field.
func (_u *CatalogModelRevisionUpdateOne) AddOperatorVersion(v int64) *CatalogModelRevisionUpdateOne {
	_u.mutation.AddOperatorVersion(v)
	return _u
}

// SetPricingSource sets the "pricing_source" field.
func (_u *CatalogModelRevisionUpdateOne) SetPricingSource(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetPricingSource(v)
	return _u
}

// SetNillablePricingSource sets the "pricing_source" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillablePricingSource(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetPricingSource(*v)
	}
	return _u
}

// ClearPricingSource clears the value of the "pricing_source" field.
func (_u *CatalogModelRevisionUpdateOne) ClearPricingSource() *CatalogModelRevisionUpdateOne {
	_u.mutation.ClearPricingSource()
	return _u
}

// SetSourceMetadata sets the "source_metadata" field.
func (_u *CatalogModelRevisionUpdateOne) SetSourceMetadata(v map[string]interface{}) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetSourceMetadata(v)
	return _u
}

// SetSourceHash sets the "source_hash" field.
func (_u *CatalogModelRevisionUpdateOne) SetSourceHash(v string) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetSourceHash(v)
	return _u
}

// SetNillableSourceHash sets the "source_hash" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableSourceHash(v *string) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetSourceHash(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CatalogModelRevisionUpdateOne) SetCreatedAt(v time.Time) *CatalogModelRevisionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CatalogModelRevisionUpdateOne) SetNillableCreatedAt(v *time.Time) *CatalogModelRevisionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CatalogModelRevisionMutation object of the builder.
func (_u *CatalogModelRevisionUpdateOne) Mutation() *CatalogModelRevisionMutation {
	return _u.mutation
}

// Where appends a list predicates to the CatalogModelRevisionUpdate builder.
func (_u *CatalogModelRevisionUpdateOne) Where(ps ...predicate.CatalogModelRevision) *CatalogModelRevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CatalogModelRevisionUpdateOne) Select(field string, fields ...string) *CatalogModelRevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CatalogModelRevision entity.
func (_u *CatalogModelRevisionUpdateOne) Save(ctx context.Context) (*CatalogModelRevision, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogModelRevisionUpdateOne) SaveX(ctx context.Context) *CatalogModelRevision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CatalogModelRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogModelRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CatalogModelRevisionUpdateOne) sqlSave(ctx context.Context) (_node *CatalogModelRevision, err error) {
	_spec := sqlgraph.NewUpdateSpec(catalogmodelrevision.Table, catalogmodelrevision.Columns, sqlgraph.NewFieldSpec(catalogmodelrevision.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CatalogModelRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, catalogmodelrevision.FieldID)
		for _, f := range fields {
			if !catalogmodelrevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != catalogmodelrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CatalogRevisionID(); ok {
		_spec.SetField(catalogmodelrevision.FieldCatalogRevisionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCatalogRevisionID(); ok {
		_spec.AddField(catalogmodelrevision.FieldCatalogRevisionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(catalogmodelrevision.FieldModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(catalogmodelrevision.FieldModelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceState(); ok {
		_spec.SetField(catalogmodelrevision.FieldSourceState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(catalogmodelrevision.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(catalogmodelrevision.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(catalogmodelrevision.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(catalogmodelrevision.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(catalogmodelrevision.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(catalogmodelrevision.FieldContextWindow, field.TypeInt64, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(catalogmodelrevision.FieldContextWindow, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(catalogmodelrevision.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(catalogmodelrevision.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if _u.mutation.MaxOutputTokensCleared() {
		_spec.ClearField(catalogmodelrevision.FieldMaxOutputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.PricingSchemaVersion(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricingSchemaVersion(); ok {
		_spec.AddField(catalogmodelrevision.FieldPricingSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PricingJSON(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingJSON, field.TypeJSON, value)
	}
	if _u.mutation.PricingJSONCleared() {
		_spec.ClearField(catalogmodelrevision.FieldPricingJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.PricingValid(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingValid, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OperatorState(); ok {
		_spec.SetField(catalogmodelrevision.FieldOperatorState, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorReason(); ok {
		_spec.SetField(catalogmodelrevision.FieldOperatorReason, field.TypeString, value)
	}
	if _u.mutation.OperatorReasonCleared() {
		_spec.ClearField(catalogmodelrevision.FieldOperatorReason, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorVersion(); ok {
		_spec.SetField(catalogmodelrevision.FieldOperatorVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorVersion(); ok {
		_spec.AddField(catalogmodelrevision.FieldOperatorVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PricingSource(); ok {
		_spec.SetField(catalogmodelrevision.FieldPricingSource, field.TypeString, value)
	}
	if _u.mutation.PricingSourceCleared() {
		_spec.ClearField(catalogmodelrevision.FieldPricingSource, field.TypeString)
	}
	if value, ok := _u.mutation.SourceMetadata(); ok {
		_spec.SetField(catalogmodelrevision.FieldSourceMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SourceHash(); ok {
		_spec.SetField(catalogmodelrevision.FieldSourceHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(catalogmodelrevision.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &CatalogModelRevision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogmodelrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
