// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catalogrevision"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CatalogRevisionUpdate is the builder for updating CatalogRevision entities.
type CatalogRevisionUpdate struct {
	config
	hooks    []Hook
	mutation *CatalogRevisionMutation
}

// Where appends a list predicates to the CatalogRevisionUpdate builder.
func (_u *CatalogRevisionUpdate) Where(ps ...predicate.CatalogRevision) *CatalogRevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *CatalogRevisionUpdate) SetRevision(v int64) *CatalogRevisionUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableRevision(v *int64) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *CatalogRevisionUpdate) AddRevision(v int64) *CatalogRevisionUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetSyncRunID sets the "sync_run_id" field.
func (_u *CatalogRevisionUpdate) SetSyncRunID(v int64) *CatalogRevisionUpdate {
	_u.mutation.ResetSyncRunID()
	_u.mutation.SetSyncRunID(v)
	return _u
}

// SetNillableSyncRunID sets the "sync_run_id" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableSyncRunID(v *int64) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetSyncRunID(*v)
	}
	return _u
}

// AddSyncRunID adds value to the "sync_run_id" field.
func (_u *CatalogRevisionUpdate) AddSyncRunID(v int64) *CatalogRevisionUpdate {
	_u.mutation.AddSyncRunID(v)
	return _u
}

// SetNormalizedHash sets the "normalized_hash" field.
func (_u *CatalogRevisionUpdate) SetNormalizedHash(v string) *CatalogRevisionUpdate {
	_u.mutation.SetNormalizedHash(v)
	return _u
}

// SetNillableNormalizedHash sets the "normalized_hash" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableNormalizedHash(v *string) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetNormalizedHash(*v)
	}
	return _u
}

// SetNormalizerVersion sets the "normalizer_version" field.
func (_u *CatalogRevisionUpdate) SetNormalizerVersion(v string) *CatalogRevisionUpdate {
	_u.mutation.SetNormalizerVersion(v)
	return _u
}

// SetNillableNormalizerVersion sets the "normalizer_version" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableNormalizerVersion(v *string) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetNormalizerVersion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *CatalogRevisionUpdate) SetState(v string) *CatalogRevisionUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableState(v *string) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetModelCount sets the "model_count" field.
func (_u *CatalogRevisionUpdate) SetModelCount(v int) *CatalogRevisionUpdate {
	_u.mutation.ResetModelCount()
	_u.mutation.SetModelCount(v)
	return _u
}

// SetNillableModelCount sets the "model_count" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableModelCount(v *int) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetModelCount(*v)
	}
	return _u
}

// AddModelCount adds value to the "model_count" field.
func (_u *CatalogRevisionUpdate) AddModelCount(v int) *CatalogRevisionUpdate {
	_u.mutation.AddModelCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CatalogRevisionUpdate) SetCreatedAt(v time.Time) *CatalogRevisionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableCreatedAt(v *time.Time) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetValidatedAt sets the "validated_at" field.
func (_u *CatalogRevisionUpdate) SetValidatedAt(v time.Time) *CatalogRevisionUpdate {
	_u.mutation.SetValidatedAt(v)
	return _u
}

// SetNillableValidatedAt sets the "validated_at" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillableValidatedAt(v *time.Time) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetValidatedAt(*v)
	}
	return _u
}

// ClearValidatedAt clears the value of the "validated_at" field.
func (_u *CatalogRevisionUpdate) ClearValidatedAt() *CatalogRevisionUpdate {
	_u.mutation.ClearValidatedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *CatalogRevisionUpdate) SetPublishedAt(v time.Time) *CatalogRevisionUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *CatalogRevisionUpdate) SetNillablePublishedAt(v *time.Time) *CatalogRevisionUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *CatalogRevisionUpdate) ClearPublishedAt() *CatalogRevisionUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the CatalogRevisionMutation object of the builder.
func (_u *CatalogRevisionUpdate) Mutation() *CatalogRevisionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CatalogRevisionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CatalogRevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogRevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CatalogRevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(catalogrevision.Table, catalogrevision.Columns, sqlgraph.NewFieldSpec(catalogrevision.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(catalogrevision.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(catalogrevision.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SyncRunID(); ok {
		_spec.SetField(catalogrevision.FieldSyncRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSyncRunID(); ok {
		_spec.AddField(catalogrevision.FieldSyncRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NormalizedHash(); ok {
		_spec.SetField(catalogrevision.FieldNormalizedHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizerVersion(); ok {
		_spec.SetField(catalogrevision.FieldNormalizerVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(catalogrevision.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelCount(); ok {
		_spec.SetField(catalogrevision.FieldModelCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedModelCount(); ok {
		_spec.AddField(catalogrevision.FieldModelCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(catalogrevision.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidatedAt(); ok {
		_spec.SetField(catalogrevision.FieldValidatedAt, field.TypeTime, value)
	}
	if _u.mutation.ValidatedAtCleared() {
		_spec.ClearField(catalogrevision.FieldValidatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(catalogrevision.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(catalogrevision.FieldPublishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CatalogRevisionUpdateOne is the builder for updating a single CatalogRevision entity.
type CatalogRevisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CatalogRevisionMutation
}

// SetRevision sets the "revision" field.
func (_u *CatalogRevisionUpdateOne) SetRevision(v int64) *CatalogRevisionUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableRevision(v *int64) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *CatalogRevisionUpdateOne) AddRevision(v int64) *CatalogRevisionUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetSyncRunID sets the "sync_run_id" field.
func (_u *CatalogRevisionUpdateOne) SetSyncRunID(v int64) *CatalogRevisionUpdateOne {
	_u.mutation.ResetSyncRunID()
	_u.mutation.SetSyncRunID(v)
	return _u
}

// SetNillableSyncRunID sets the "sync_run_id" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableSyncRunID(v *int64) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetSyncRunID(*v)
	}
	return _u
}

// AddSyncRunID adds value to the "sync_run_id" field.
func (_u *CatalogRevisionUpdateOne) AddSyncRunID(v int64) *CatalogRevisionUpdateOne {
	_u.mutation.AddSyncRunID(v)
	return _u
}

// SetNormalizedHash sets the "normalized_hash" field.
func (_u *CatalogRevisionUpdateOne) SetNormalizedHash(v string) *CatalogRevisionUpdateOne {
	_u.mutation.SetNormalizedHash(v)
	return _u
}

// SetNillableNormalizedHash sets the "normalized_hash" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableNormalizedHash(v *string) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetNormalizedHash(*v)
	}
	return _u
}

// SetNormalizerVersion sets the "normalizer_version" field.
func (_u *CatalogRevisionUpdateOne) SetNormalizerVersion(v string) *CatalogRevisionUpdateOne {
	_u.mutation.SetNormalizerVersion(v)
	return _u
}

// SetNillableNormalizerVersion sets the "normalizer_version" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableNormalizerVersion(v *string) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetNormalizerVersion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *CatalogRevisionUpdateOne) SetState(v string) *CatalogRevisionUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableState(v *string) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetModelCount sets the "model_count" field.
func (_u *CatalogRevisionUpdateOne) SetModelCount(v int) *CatalogRevisionUpdateOne {
	_u.mutation.ResetModelCount()
	_u.mutation.SetModelCount(v)
	return _u
}

// SetNillableModelCount sets the "model_count" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableModelCount(v *int) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetModelCount(*v)
	}
	return _u
}

// AddModelCount adds value to the "model_count" field.
func (_u *CatalogRevisionUpdateOne) AddModelCount(v int) *CatalogRevisionUpdateOne {
	_u.mutation.AddModelCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CatalogRevisionUpdateOne) SetCreatedAt(v time.Time) *CatalogRevisionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableCreatedAt(v *time.Time) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetValidatedAt sets the "validated_at" field.
func (_u *CatalogRevisionUpdateOne) SetValidatedAt(v time.Time) *CatalogRevisionUpdateOne {
	_u.mutation.SetValidatedAt(v)
	return _u
}

// SetNillableValidatedAt sets the "validated_at" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillableValidatedAt(v *time.Time) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetValidatedAt(*v)
	}
	return _u
}

// ClearValidatedAt clears the value of the "validated_at" field.
func (_u *CatalogRevisionUpdateOne) ClearValidatedAt() *CatalogRevisionUpdateOne {
	_u.mutation.ClearValidatedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *CatalogRevisionUpdateOne) SetPublishedAt(v time.Time) *CatalogRevisionUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *CatalogRevisionUpdateOne) SetNillablePublishedAt(v *time.Time) *CatalogRevisionUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *CatalogRevisionUpdateOne) ClearPublishedAt() *CatalogRevisionUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the CatalogRevisionMutation object of the builder.
func (_u *CatalogRevisionUpdateOne) Mutation() *CatalogRevisionMutation {
	return _u.mutation
}

// Where appends a list predicates to the CatalogRevisionUpdate builder.
func (_u *CatalogRevisionUpdateOne) Where(ps ...predicate.CatalogRevision) *CatalogRevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CatalogRevisionUpdateOne) Select(field string, fields ...string) *CatalogRevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CatalogRevision entity.
func (_u *CatalogRevisionUpdateOne) Save(ctx context.Context) (*CatalogRevision, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogRevisionUpdateOne) SaveX(ctx context.Context) *CatalogRevision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CatalogRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CatalogRevisionUpdateOne) sqlSave(ctx context.Context) (_node *CatalogRevision, err error) {
	_spec := sqlgraph.NewUpdateSpec(catalogrevision.Table, catalogrevision.Columns, sqlgraph.NewFieldSpec(catalogrevision.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CatalogRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, catalogrevision.FieldID)
		for _, f := range fields {
			if !catalogrevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != catalogrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(catalogrevision.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(catalogrevision.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SyncRunID(); ok {
		_spec.SetField(catalogrevision.FieldSyncRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSyncRunID(); ok {
		_spec.AddField(catalogrevision.FieldSyncRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NormalizedHash(); ok {
		_spec.SetField(catalogrevision.FieldNormalizedHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizerVersion(); ok {
		_spec.SetField(catalogrevision.FieldNormalizerVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(catalogrevision.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelCount(); ok {
		_spec.SetField(catalogrevision.FieldModelCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedModelCount(); ok {
		_spec.AddField(catalogrevision.FieldModelCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(catalogrevision.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidatedAt(); ok {
		_spec.SetField(catalogrevision.FieldValidatedAt, field.TypeTime, value)
	}
	if _u.mutation.ValidatedAtCleared() {
		_spec.ClearField(catalogrevision.FieldValidatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(catalogrevision.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(catalogrevision.FieldPublishedAt, field.TypeTime)
	}
	_node = &CatalogRevision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
