// Code generated by ent, DO NOT EDIT.

package catalogrevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldID, id))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldRevision, v))
}

// SyncRunID applies equality check predicate on the "sync_run_id" field. It's identical to SyncRunIDEQ.
func SyncRunID(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldSyncRunID, v))
}

// NormalizedHash applies equality check predicate on the "normalized_hash" field. It's identical to NormalizedHashEQ.
func NormalizedHash(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldNormalizedHash, v))
}

// NormalizerVersion applies equality check predicate on the "normalizer_version" field. It's identical to NormalizerVersionEQ.
func NormalizerVersion(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldNormalizerVersion, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldState, v))
}

// ModelCount applies equality check predicate on the "model_count" field. It's identical to ModelCountEQ.
func ModelCount(v int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldModelCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// ValidatedAt applies equality check predicate on the "validated_at" field. It's identical to ValidatedAtEQ.
func ValidatedAt(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldValidatedAt, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldPublishedAt, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldRevision, v))
}

// SyncRunIDEQ applies the EQ predicate on the "sync_run_id" field.
func SyncRunIDEQ(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldSyncRunID, v))
}

// SyncRunIDNEQ applies the NEQ predicate on the "sync_run_id" field.
func SyncRunIDNEQ(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldSyncRunID, v))
}

// SyncRunIDIn applies the In predicate on the "sync_run_id" field.
func SyncRunIDIn(vs ...int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldSyncRunID, vs...))
}

// SyncRunIDNotIn applies the NotIn predicate on the "sync_run_id" field.
func SyncRunIDNotIn(vs ...int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldSyncRunID, vs...))
}

// SyncRunIDGT applies the GT predicate on the "sync_run_id" field.
func SyncRunIDGT(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldSyncRunID, v))
}

// SyncRunIDGTE applies the GTE predicate on the "sync_run_id" field.
func SyncRunIDGTE(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldSyncRunID, v))
}

// SyncRunIDLT applies the LT predicate on the "sync_run_id" field.
func SyncRunIDLT(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldSyncRunID, v))
}

// SyncRunIDLTE applies the LTE predicate on the "sync_run_id" field.
func SyncRunIDLTE(v int64) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldSyncRunID, v))
}

// NormalizedHashEQ applies the EQ predicate on the "normalized_hash" field.
func NormalizedHashEQ(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldNormalizedHash, v))
}

// NormalizedHashNEQ applies the NEQ predicate on the "normalized_hash" field.
func NormalizedHashNEQ(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldNormalizedHash, v))
}

// NormalizedHashIn applies the In predicate on the "normalized_hash" field.
func NormalizedHashIn(vs ...string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldNormalizedHash, vs...))
}

// NormalizedHashNotIn applies the NotIn predicate on the "normalized_hash" field.
func NormalizedHashNotIn(vs ...string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldNormalizedHash, vs...))
}

// NormalizedHashGT applies the GT predicate on the "normalized_hash" field.
func NormalizedHashGT(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldNormalizedHash, v))
}

// NormalizedHashGTE applies the GTE predicate on the "normalized_hash" field.
func NormalizedHashGTE(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldNormalizedHash, v))
}

// NormalizedHashLT applies the LT predicate on the "normalized_hash" field.
func NormalizedHashLT(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldNormalizedHash, v))
}

// NormalizedHashLTE applies the LTE predicate on the "normalized_hash" field.
func NormalizedHashLTE(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldNormalizedHash, v))
}

// NormalizedHashContains applies the Contains predicate on the "normalized_hash" field.
func NormalizedHashContains(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldContains(FieldNormalizedHash, v))
}

// NormalizedHashHasPrefix applies the HasPrefix predicate on the "normalized_hash" field.
func NormalizedHashHasPrefix(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldHasPrefix(FieldNormalizedHash, v))
}

// NormalizedHashHasSuffix applies the HasSuffix predicate on the "normalized_hash" field.
func NormalizedHashHasSuffix(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldHasSuffix(FieldNormalizedHash, v))
}

// NormalizedHashEqualFold applies the EqualFold predicate on the "normalized_hash" field.
func NormalizedHashEqualFold(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEqualFold(FieldNormalizedHash, v))
}

// NormalizedHashContainsFold applies the ContainsFold predicate on the "normalized_hash" field.
func NormalizedHashContainsFold(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldContainsFold(FieldNormalizedHash, v))
}

// NormalizerVersionEQ applies the EQ predicate on the "normalizer_version" field.
func NormalizerVersionEQ(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldNormalizerVersion, v))
}

// NormalizerVersionNEQ applies the NEQ predicate on the "normalizer_version" field.
func NormalizerVersionNEQ(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldNormalizerVersion, v))
}

// NormalizerVersionIn applies the In predicate on the "normalizer_version" field.
func NormalizerVersionIn(vs ...string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldNormalizerVersion, vs...))
}

// NormalizerVersionNotIn applies the NotIn predicate on the "normalizer_version" field.
func NormalizerVersionNotIn(vs ...string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldNormalizerVersion, vs...))
}

// NormalizerVersionGT applies the GT predicate on the "normalizer_version" field.
func NormalizerVersionGT(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldNormalizerVersion, v))
}

// NormalizerVersionGTE applies the GTE predicate on the "normalizer_version" field.
func NormalizerVersionGTE(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldNormalizerVersion, v))
}

// NormalizerVersionLT applies the LT predicate on the "normalizer_version" field.
func NormalizerVersionLT(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldNormalizerVersion, v))
}

// NormalizerVersionLTE applies the LTE predicate on the "normalizer_version" field.
func NormalizerVersionLTE(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldNormalizerVersion, v))
}

// NormalizerVersionContains applies the Contains predicate on the "normalizer_version" field.
func NormalizerVersionContains(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldContains(FieldNormalizerVersion, v))
}

// NormalizerVersionHasPrefix applies the HasPrefix predicate on the "normalizer_version" field.
func NormalizerVersionHasPrefix(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldHasPrefix(FieldNormalizerVersion, v))
}

// NormalizerVersionHasSuffix applies the HasSuffix predicate on the "normalizer_version" field.
func NormalizerVersionHasSuffix(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldHasSuffix(FieldNormalizerVersion, v))
}

// NormalizerVersionEqualFold applies the EqualFold predicate on the "normalizer_version" field.
func NormalizerVersionEqualFold(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEqualFold(FieldNormalizerVersion, v))
}

// NormalizerVersionContainsFold applies the ContainsFold predicate on the "normalizer_version" field.
func NormalizerVersionContainsFold(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldContainsFold(FieldNormalizerVersion, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldContainsFold(FieldState, v))
}

// ModelCountEQ applies the EQ predicate on the "model_count" field.
func ModelCountEQ(v int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldModelCount, v))
}

// ModelCountNEQ applies the NEQ predicate on the "model_count" field.
func ModelCountNEQ(v int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldModelCount, v))
}

// ModelCountIn applies the In predicate on the "model_count" field.
func ModelCountIn(vs ...int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldModelCount, vs...))
}

// ModelCountNotIn applies the NotIn predicate on the "model_count" field.
func ModelCountNotIn(vs ...int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldModelCount, vs...))
}

// ModelCountGT applies the GT predicate on the "model_count" field.
func ModelCountGT(v int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldModelCount, v))
}

// ModelCountGTE applies the GTE predicate on the "model_count" field.
func ModelCountGTE(v int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldModelCount, v))
}

// ModelCountLT applies the LT predicate on the "model_count" field.
func ModelCountLT(v int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldModelCount, v))
}

// ModelCountLTE applies the LTE predicate on the "model_count" field.
func ModelCountLTE(v int) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldModelCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// ValidatedAtEQ applies the EQ predicate on the "validated_at" field.
func ValidatedAtEQ(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldValidatedAt, v))
}

// ValidatedAtNEQ applies the NEQ predicate on the "validated_at" field.
func ValidatedAtNEQ(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldValidatedAt, v))
}

// ValidatedAtIn applies the In predicate on the "validated_at" field.
func ValidatedAtIn(vs ...time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldValidatedAt, vs...))
}

// ValidatedAtNotIn applies the NotIn predicate on the "validated_at" field.
func ValidatedAtNotIn(vs ...time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldValidatedAt, vs...))
}

// ValidatedAtGT applies the GT predicate on the "validated_at" field.
func ValidatedAtGT(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldValidatedAt, v))
}

// ValidatedAtGTE applies the GTE predicate on the "validated_at" field.
func ValidatedAtGTE(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldValidatedAt, v))
}

// ValidatedAtLT applies the LT predicate on the "validated_at" field.
func ValidatedAtLT(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldValidatedAt, v))
}

// ValidatedAtLTE applies the LTE predicate on the "validated_at" field.
func ValidatedAtLTE(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldValidatedAt, v))
}

// ValidatedAtIsNil applies the IsNil predicate on the "validated_at" field.
func ValidatedAtIsNil() predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIsNull(FieldValidatedAt))
}

// ValidatedAtNotNil applies the NotNil predicate on the "validated_at" field.
func ValidatedAtNotNil() predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotNull(FieldValidatedAt))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.FieldNotNull(FieldPublishedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CatalogRevision) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CatalogRevision) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CatalogRevision) predicate.CatalogRevision {
	return predicate.CatalogRevision(sql.NotPredicates(p))
}
