// Code generated by ent, DO NOT EDIT.

package catalogpublication

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the catalogpublication type in the database.
	Label = "catalog_publication"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldActiveRevisionID holds the string denoting the active_revision_id field in the database.
	FieldActiveRevisionID = "active_revision_id"
	// FieldEpoch holds the string denoting the epoch field in the database.
	FieldEpoch = "epoch"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the catalogpublication in the database.
	Table = "catalog_publications"
)

// Columns holds all SQL columns for catalogpublication fields.
var Columns = []string{
	FieldID,
	FieldScope,
	FieldActiveRevisionID,
	FieldEpoch,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CatalogPublication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByActiveRevisionID orders the results by the active_revision_id field.
func ByActiveRevisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveRevisionID, opts...).ToFunc()
}

// ByEpoch orders the results by the epoch field.
func ByEpoch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEpoch, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
