// Code generated by ent, DO NOT EDIT.

package balancepackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCode, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldDescription, v))
}

// AmountLedger applies equality check predicate on the "amount_ledger" field. It's identical to AmountLedgerEQ.
func AmountLedger(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldAmountLedger, v))
}

// CreditLedger applies equality check predicate on the "credit_ledger" field. It's identical to CreditLedgerEQ.
func CreditLedger(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreditLedger, v))
}

// BonusLedger applies equality check predicate on the "bonus_ledger" field. It's identical to BonusLedgerEQ.
func BonusLedger(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldBonusLedger, v))
}

// CreditMultiplier applies equality check predicate on the "credit_multiplier" field. It's identical to CreditMultiplierEQ.
func CreditMultiplier(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreditMultiplier, v))
}

// Badge applies equality check predicate on the "badge" field. It's identical to BadgeEQ.
func Badge(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldBadge, v))
}

// Popular applies equality check predicate on the "popular" field. It's identical to PopularEQ.
func Popular(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldPopular, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldCode, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldLabel, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldDescription, v))
}

// AmountLedgerEQ applies the EQ predicate on the "amount_ledger" field.
func AmountLedgerEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldAmountLedger, v))
}

// AmountLedgerNEQ applies the NEQ predicate on the "amount_ledger" field.
func AmountLedgerNEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldAmountLedger, v))
}

// AmountLedgerIn applies the In predicate on the "amount_ledger" field.
func AmountLedgerIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldAmountLedger, vs...))
}

// AmountLedgerNotIn applies the NotIn predicate on the "amount_ledger" field.
func AmountLedgerNotIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldAmountLedger, vs...))
}

// AmountLedgerGT applies the GT predicate on the "amount_ledger" field.
func AmountLedgerGT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldAmountLedger, v))
}

// AmountLedgerGTE applies the GTE predicate on the "amount_ledger" field.
func AmountLedgerGTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldAmountLedger, v))
}

// AmountLedgerLT applies the LT predicate on the "amount_ledger" field.
func AmountLedgerLT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldAmountLedger, v))
}

// AmountLedgerLTE applies the LTE predicate on the "amount_ledger" field.
func AmountLedgerLTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldAmountLedger, v))
}

// CreditLedgerEQ applies the EQ predicate on the "credit_ledger" field.
func CreditLedgerEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreditLedger, v))
}

// CreditLedgerNEQ applies the NEQ predicate on the "credit_ledger" field.
func CreditLedgerNEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldCreditLedger, v))
}

// CreditLedgerIn applies the In predicate on the "credit_ledger" field.
func CreditLedgerIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldCreditLedger, vs...))
}

// CreditLedgerNotIn applies the NotIn predicate on the "credit_ledger" field.
func CreditLedgerNotIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldCreditLedger, vs...))
}

// CreditLedgerGT applies the GT predicate on the "credit_ledger" field.
func CreditLedgerGT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldCreditLedger, v))
}

// CreditLedgerGTE applies the GTE predicate on the "credit_ledger" field.
func CreditLedgerGTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldCreditLedger, v))
}

// CreditLedgerLT applies the LT predicate on the "credit_ledger" field.
func CreditLedgerLT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldCreditLedger, v))
}

// CreditLedgerLTE applies the LTE predicate on the "credit_ledger" field.
func CreditLedgerLTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldCreditLedger, v))
}

// BonusLedgerEQ applies the EQ predicate on the "bonus_ledger" field.
func BonusLedgerEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldBonusLedger, v))
}

// BonusLedgerNEQ applies the NEQ predicate on the "bonus_ledger" field.
func BonusLedgerNEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldBonusLedger, v))
}

// BonusLedgerIn applies the In predicate on the "bonus_ledger" field.
func BonusLedgerIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldBonusLedger, vs...))
}

// BonusLedgerNotIn applies the NotIn predicate on the "bonus_ledger" field.
func BonusLedgerNotIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldBonusLedger, vs...))
}

// BonusLedgerGT applies the GT predicate on the "bonus_ledger" field.
func BonusLedgerGT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldBonusLedger, v))
}

// BonusLedgerGTE applies the GTE predicate on the "bonus_ledger" field.
func BonusLedgerGTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldBonusLedger, v))
}

// BonusLedgerLT applies the LT predicate on the "bonus_ledger" field.
func BonusLedgerLT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldBonusLedger, v))
}

// BonusLedgerLTE applies the LTE predicate on the "bonus_ledger" field.
func BonusLedgerLTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldBonusLedger, v))
}

// CreditMultiplierEQ applies the EQ predicate on the "credit_multiplier" field.
func CreditMultiplierEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreditMultiplier, v))
}

// CreditMultiplierNEQ applies the NEQ predicate on the "credit_multiplier" field.
func CreditMultiplierNEQ(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldCreditMultiplier, v))
}

// CreditMultiplierIn applies the In predicate on the "credit_multiplier" field.
func CreditMultiplierIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldCreditMultiplier, vs...))
}

// CreditMultiplierNotIn applies the NotIn predicate on the "credit_multiplier" field.
func CreditMultiplierNotIn(vs ...float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldCreditMultiplier, vs...))
}

// CreditMultiplierGT applies the GT predicate on the "credit_multiplier" field.
func CreditMultiplierGT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldCreditMultiplier, v))
}

// CreditMultiplierGTE applies the GTE predicate on the "credit_multiplier" field.
func CreditMultiplierGTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldCreditMultiplier, v))
}

// CreditMultiplierLT applies the LT predicate on the "credit_multiplier" field.
func CreditMultiplierLT(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldCreditMultiplier, v))
}

// CreditMultiplierLTE applies the LTE predicate on the "credit_multiplier" field.
func CreditMultiplierLTE(v float64) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldCreditMultiplier, v))
}

// BadgeEQ applies the EQ predicate on the "badge" field.
func BadgeEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldBadge, v))
}

// BadgeNEQ applies the NEQ predicate on the "badge" field.
func BadgeNEQ(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldBadge, v))
}

// BadgeIn applies the In predicate on the "badge" field.
func BadgeIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldBadge, vs...))
}

// BadgeNotIn applies the NotIn predicate on the "badge" field.
func BadgeNotIn(vs ...string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldBadge, vs...))
}

// BadgeGT applies the GT predicate on the "badge" field.
func BadgeGT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldBadge, v))
}

// BadgeGTE applies the GTE predicate on the "badge" field.
func BadgeGTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldBadge, v))
}

// BadgeLT applies the LT predicate on the "badge" field.
func BadgeLT(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldBadge, v))
}

// BadgeLTE applies the LTE predicate on the "badge" field.
func BadgeLTE(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldBadge, v))
}

// BadgeContains applies the Contains predicate on the "badge" field.
func BadgeContains(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContains(FieldBadge, v))
}

// BadgeHasPrefix applies the HasPrefix predicate on the "badge" field.
func BadgeHasPrefix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasPrefix(FieldBadge, v))
}

// BadgeHasSuffix applies the HasSuffix predicate on the "badge" field.
func BadgeHasSuffix(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldHasSuffix(FieldBadge, v))
}

// BadgeEqualFold applies the EqualFold predicate on the "badge" field.
func BadgeEqualFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEqualFold(FieldBadge, v))
}

// BadgeContainsFold applies the ContainsFold predicate on the "badge" field.
func BadgeContainsFold(v string) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldContainsFold(FieldBadge, v))
}

// PopularEQ applies the EQ predicate on the "popular" field.
func PopularEQ(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldPopular, v))
}

// PopularNEQ applies the NEQ predicate on the "popular" field.
func PopularNEQ(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldPopular, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BalancePackage {
	return predicate.BalancePackage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalancePackage) predicate.BalancePackage {
	return predicate.BalancePackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalancePackage) predicate.BalancePackage {
	return predicate.BalancePackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalancePackage) predicate.BalancePackage {
	return predicate.BalancePackage(sql.NotPredicates(p))
}
