// Code generated by ent, DO NOT EDIT.

package catalogmodelrevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the catalogmodelrevision type in the database.
	Label = "catalog_model_revision"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCatalogRevisionID holds the string denoting the catalog_revision_id field in the database.
	FieldCatalogRevisionID = "catalog_revision_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldSourceState holds the string denoting the source_state field in the database.
	FieldSourceState = "source_state"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldContextWindow holds the string denoting the context_window field in the database.
	FieldContextWindow = "context_window"
	// FieldMaxOutputTokens holds the string denoting the max_output_tokens field in the database.
	FieldMaxOutputTokens = "max_output_tokens"
	// FieldPricingSchemaVersion holds the string denoting the pricing_schema_version field in the database.
	FieldPricingSchemaVersion = "pricing_schema_version"
	// FieldPricingJSON holds the string denoting the pricing_json field in the database.
	FieldPricingJSON = "pricing_json"
	// FieldPricingValid holds the string denoting the pricing_valid field in the database.
	FieldPricingValid = "pricing_valid"
	// FieldOperatorState holds the string denoting the operator_state field in the database.
	FieldOperatorState = "operator_state"
	// FieldOperatorReason holds the string denoting the operator_reason field in the database.
	FieldOperatorReason = "operator_reason"
	// FieldOperatorVersion holds the string denoting the operator_version field in the database.
	FieldOperatorVersion = "operator_version"
	// FieldPricingSource holds the string denoting the pricing_source field in the database.
	FieldPricingSource = "pricing_source"
	// FieldSourceMetadata holds the string denoting the source_metadata field in the database.
	FieldSourceMetadata = "source_metadata"
	// FieldSourceHash holds the string denoting the source_hash field in the database.
	FieldSourceHash = "source_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the catalogmodelrevision in the database.
	Table = "catalog_model_revisions"
)

// Columns holds all SQL columns for catalogmodelrevision fields.
var Columns = []string{
	FieldID,
	FieldCatalogRevisionID,
	FieldModelID,
	FieldSourceState,
	FieldProvider,
	FieldPlatform,
	FieldMode,
	FieldCapabilities,
	FieldContextWindow,
	FieldMaxOutputTokens,
	FieldPricingSchemaVersion,
	FieldPricingJSON,
	FieldPricingValid,
	FieldOperatorState,
	FieldOperatorReason,
	FieldOperatorVersion,
	FieldPricingSource,
	FieldSourceMetadata,
	FieldSourceHash,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCapabilities holds the default value on creation for the "capabilities" field.
	DefaultCapabilities map[string]interface{}
	// DefaultPricingValid holds the default value on creation for the "pricing_valid" field.
	DefaultPricingValid bool
	// DefaultOperatorState holds the default value on creation for the "operator_state" field.
	DefaultOperatorState string
	// DefaultOperatorVersion holds the default value on creation for the "operator_version" field.
	DefaultOperatorVersion int64
	// DefaultSourceMetadata holds the default value on creation for the "source_metadata" field.
	DefaultSourceMetadata map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CatalogModelRevision queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCatalogRevisionID orders the results by the catalog_revision_id field.
func ByCatalogRevisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCatalogRevisionID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// BySourceState orders the results by the source_state field.
func BySourceState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceState, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByContextWindow orders the results by the context_window field.
func ByContextWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextWindow, opts...).ToFunc()
}

// ByMaxOutputTokens orders the results by the max_output_tokens field.
func ByMaxOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxOutputTokens, opts...).ToFunc()
}

// ByPricingSchemaVersion orders the results by the pricing_schema_version field.
func ByPricingSchemaVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingSchemaVersion, opts...).ToFunc()
}

// ByPricingValid orders the results by the pricing_valid field.
func ByPricingValid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingValid, opts...).ToFunc()
}

// ByOperatorState orders the results by the operator_state field.
func ByOperatorState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorState, opts...).ToFunc()
}

// ByOperatorReason orders the results by the operator_reason field.
func ByOperatorReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorReason, opts...).ToFunc()
}

// ByOperatorVersion orders the results by the operator_version field.
func ByOperatorVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorVersion, opts...).ToFunc()
}

// ByPricingSource orders the results by the pricing_source field.
func ByPricingSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingSource, opts...).ToFunc()
}

// BySourceHash orders the results by the source_hash field.
func BySourceHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
